syntax = "proto3";

package as3pb.bench;

message BenchAddress {
  string street = 1;
  string city = 2;
  string state = 3;
  string zip = 4;

  repeated BenchAddressMetadata metadata = 10;
}

message BenchAddressMetadata {
  repeated uint32 lucky_numbers = 1;
  repeated sfixed64 big_lucky_numbers = 2;
  sint32 a_field = 3;
  int64 b_field = 4;
  float c_field = 5;
  double d_field = 6;
  bool e_field = 7;
  bytes f_field = 8;
}

message BenchCreateAddressRequest {
  BenchAddress address = 1;
}

message BenchCreateAddressResponse {
  bool success = 1;
  string id = 2;
}

message BenchDeleteAddressRequest {
  string id = 1;
}

message BenchDeleteAddressResponse {
  bool success = 1;
  string id = 2;
}
