package internal_test

import (
	"strings"
	"testing"

	"github.com/33TU/as3pb/internal"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestGenerateFileEnum(t *testing.T) {
	plugin := enumPlugin(t, true)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	files := plugin.Response().GetFile()
	if len(files) != 1 {
		t.Fatalf("generated %d files, want 1", len(files))
	}
	if got, want := files[0].GetName(), "test/v1/PlayerStatus.as"; got != want {
		t.Fatalf("generated file name = %q, want %q", got, want)
	}

	want := `/**
 * Code generated by protoc-gen-as3.
 * Source: test.proto
 */
package test.v1
{
    public final class PlayerStatus
    {
        public static const PLAYER_STATUS_UNKNOWN:uint = 0;
        public static const PLAYER_STATUS_ACTIVE:uint = 1;
    }
}
`
	if got := files[0].GetContent(); got != want {
		t.Fatalf("generated content:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateFileSkipsNonGeneratedFile(t *testing.T) {
	plugin := enumPlugin(t, false)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}
	if got := len(plugin.Response().GetFile()); got != 0 {
		t.Fatalf("generated %d files, want 0", got)
	}
}

func TestGenerateFileRejectsProto2(t *testing.T) {
	plugin := syntaxPlugin(t, "proto2")
	generator := internal.NewGenerator(plugin, internal.Options{})

	err := generator.GenerateFile(plugin.Files[0])
	if err == nil {
		t.Fatal("GenerateFile() error = nil, want proto2 rejection")
	}
	if !strings.Contains(err.Error(), "only proto3 and editions files are supported") {
		t.Fatalf("GenerateFile() error = %q, want proto2 rejection", err)
	}
}

func TestGenerateFileMessageFieldsAndReset(t *testing.T) {
	plugin := messagePlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	files := plugin.Response().GetFile()
	if len(files) != 1 {
		t.Fatalf("generated %d files, want 1", len(files))
	}
	if got, want := files[0].GetName(), "test/v1/Player.as"; got != want {
		t.Fatalf("generated file name = %q, want %q", got, want)
	}

	content := files[0].GetContent()
	wantParts := []string{
		"import flash.utils.ByteArray;",
		"import as3pb.proto.Deserialize;",
		"import as3pb.proto.Serialize;",
		"import as3pb.proto.Buffers;",
		"import as3pb.types.Int64;",
		"import as3pb.wkt.AnyRegistry;",
		`public static const TYPE_URL:String = "type.googleapis.com/test.v1.Player";`,
		"public static const FIELD_MOVE:uint = 5;",
		"public var raw:ByteArray = Buffers.newByteArray();",
		"public static function reset(msg:test.v1.Player):void",
		"msg.raw.length = 0;",
		"public static function clone(src:test.v1.Player):test.v1.Player",
		"const dst:test.v1.Player = new test.v1.Player();",
		"dst.raw = Buffers.cloneByteArray(src.raw);",
		"dst.amount.copyFrom(src.amount);",
		"dst.move = test.v1.Player.clone(src.move);",
		"if (src.choiceAmount)",
		"dst.choiceAmount.copyFrom(src.choiceAmount);",
		"if (src.choiceBytes)",
		"dst.choiceBytes = Buffers.cloneByteArray(src.choiceBytes);",
		"public static function deserializeBytes(src:ByteArray, dst:test.v1.Player = null, limit:uint = 0, reset:Boolean = true):test.v1.Player",
		`throw new Error("Invalid protobuf message limit");`,
		`throw new Error("Invalid protobuf field number");`,
		"else",
		"dst.actionCase = FIELD_MOVE;",
		"case 32:",
		"dst.scores.push(Deserialize.readInt32(src));",
		"dst.move = test.v1.Player.deserializeBytes(src, dst.move, src.position + messageLength, dst.actionCase != FIELD_MOVE);",
		"Deserialize.readInt32Vector(src, dst.scores);",
		"public static function serializeBytes(src:test.v1.Player, dst:ByteArray):void",
		"if (!src)",
		"const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;",
		"if (localAmount.low || localAmount.high)",
		"Serialize.writeVarint64s(dst, localChoiceAmount ? localChoiceAmount.low : 0, localChoiceAmount ? localChoiceAmount.high : 0);",
		"if (localChoiceText != null)",
		"Serialize.writeString(dst, localChoiceText, reuseBuffer);",
		"if (localChoiceBytes != null)",
		"Serialize.writeBytes(dst, localChoiceBytes);",
		"Serialize.writeInt32Vector(dst, localScores, reuseBuffer, vecLength);",
		"if (localRatio != 0.0)",
		"switch (src.actionCase)",
		"AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated content missing %q:\n%s", want, content)
		}
	}
	if strings.Contains(content, "var vecIndex:uint") {
		t.Fatalf("packed-only generated content contains vecIndex:\n%s", content)
	}
	for _, unwanted := range []string{
		"import as3pb.types.UInt64;",
		"import as3pb.types.Int64Vector;",
		"import as3pb.types.UInt64Vector;",
	} {
		if strings.Contains(content, unwanted) {
			t.Fatalf("generated content contains unused %q:\n%s", unwanted, content)
		}
	}
}

func TestGenerateFileCanDisableInlineReset(t *testing.T) {
	plugin := messagePlugin(t)
	inlineReset := false
	generator := internal.NewGenerator(plugin, internal.Options{InlineReset: &inlineReset})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "[Inline]") {
		t.Fatalf("generated content contains [Inline]:\n%s", content)
	}
	if !strings.Contains(content, "public static function reset(msg:test.v1.Player):void") {
		t.Fatalf("generated content missing reset method:\n%s", content)
	}
}

func TestGenerateFileCanDisableClone(t *testing.T) {
	plugin := messagePlugin(t)
	generateClone := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateClone: &generateClone})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "public static function clone") {
		t.Fatalf("generated content contains clone:\n%s", content)
	}
	for _, want := range []string{
		"public static function reset",
		"public static function deserializeBytes",
		"public static function serializeBytes",
	} {
		if !strings.Contains(content, want) {
			t.Fatalf("generated content missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileCanDisableSerialize(t *testing.T) {
	plugin := messagePlugin(t)
	generateSerialize := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateSerialize: &generateSerialize})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "public static function serializeBytes") {
		t.Fatalf("generated content contains serializeBytes:\n%s", content)
	}
	if strings.Contains(content, "import as3pb.proto.Serialize;") {
		t.Fatalf("generated content contains Serialize import:\n%s", content)
	}
	if !strings.Contains(content, "public static function deserializeBytes") {
		t.Fatalf("generated content missing deserializeBytes:\n%s", content)
	}
}

func TestGenerateFileCanDisableDeserialize(t *testing.T) {
	plugin := messagePlugin(t)
	generateDeserialize := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateDeserialize: &generateDeserialize})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "public static function deserializeBytes") {
		t.Fatalf("generated content contains deserializeBytes:\n%s", content)
	}
	if strings.Contains(content, "import as3pb.proto.Deserialize;") {
		t.Fatalf("generated content contains Deserialize import:\n%s", content)
	}
	if !strings.Contains(content, "public static function serializeBytes") {
		t.Fatalf("generated content missing serializeBytes:\n%s", content)
	}
}

func TestGenerateFileMapsProtobufAnyToRuntimeType(t *testing.T) {
	plugin := anyPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[1]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	wantParts := []string{
		"import google.protobuf.Any;",
		"public var payload:google.protobuf.Any = null;",
		"dst.payload = google.protobuf.Any.deserializeBytes(src, dst.payload, src.position + messageLength, false);",
		"google.protobuf.Any.serializeBytes(localPayload, messageReuseBuffer);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated Any field missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileProto3OptionalFields(t *testing.T) {
	plugin := optionalPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	wantParts := []string{
		"import as3pb.types.OptionalInt;",
		"import as3pb.types.UInt64;",
		"public var count:OptionalInt = null;",
		"public var label_:String = null;",
		"public var total:UInt64 = null;",
		"msg.count = null;",
		"if (dst.count == null)",
		"dst.count = new OptionalInt();",
		"if (localCount != null)",
		"if (localTotal != null)",
		"Serialize.writeInt32(dst, localCount.value);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated optional field missing %q:\n%s", want, content)
		}
	}
	for _, unwanted := range []string{"FIELD_COUNT", "countCase", "_countCase"} {
		if strings.Contains(content, unwanted) {
			t.Fatalf("generated optional field exposes synthetic oneof %q:\n%s", unwanted, content)
		}
	}
}

func TestGenerateFileSkipsRuntimeProvidedAny(t *testing.T) {
	plugin := anyPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{GenerateAlways: true})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}
	if files := plugin.Response().GetFile(); len(files) != 0 {
		t.Fatalf("GenerateFile() generated %d files for runtime-provided Any, want 0", len(files))
	}
}

func TestGenerateFileGeneratesExplicitAny(t *testing.T) {
	plugin := anyPlugin(t)
	plugin.Files[0].Generate = true
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}
	files := plugin.Response().GetFile()
	if len(files) != 1 || files[0].GetName() != "google/protobuf/Any.as" {
		t.Fatalf("GenerateFile() files = %#v, want google/protobuf/Any.as", files)
	}
}

func TestGenerateFileCanDisableAnyRegistration(t *testing.T) {
	plugin := anyPlugin(t)
	generateAny := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateAny: &generateAny})

	if err := generator.GenerateFile(plugin.Files[1]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "TYPE_URL") {
		t.Fatalf("generated content contains TYPE_URL:\n%s", content)
	}
	if strings.Contains(content, "AnyRegistry") {
		t.Fatalf("generated content contains AnyRegistry:\n%s", content)
	}
	if !strings.Contains(content, "import google.protobuf.Any;") {
		t.Fatalf("generated content missing Any field support:\n%s", content)
	}
}

func TestGenerateFileRejectsServicesWhenCodecsDisabled(t *testing.T) {
	plugin := servicePlugin(t)
	generateSerialize := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateSerialize: &generateSerialize})

	err := generator.GenerateFile(plugin.Files[0])
	if err == nil {
		t.Fatal("GenerateFile() error = nil, want service codec rejection")
	}
	if !strings.Contains(err.Error(), "services require serialize and deserialize") {
		t.Fatalf("GenerateFile() error = %q, want service codec rejection", err)
	}
}

func TestGenerateWriteTagUsesConstantFastPaths(t *testing.T) {
	plugin := highTagPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	wantParts := []string{
		"dst.writeShort(384);",
		"dst.writeByte(128);",
		"dst.writeShort(32896);",
		"dst.writeShort(32896);",
		"dst.writeShort(32896);",
		"dst.writeByte(1);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated content missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileService(t *testing.T) {
	plugin := servicePlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	var content string
	for _, file := range plugin.Response().GetFile() {
		if file.GetName() == "test/v1/GreeterRpcClient.as" {
			content = file.GetContent()
			break
		}
	}
	if content == "" {
		t.Fatalf("missing generated GreeterRpcClient.as; files: %v", plugin.Response().GetFile())
	}

	wantParts := []string{
		"public final class GreeterRpcClient extends RpcClient",
		"import as3pb.rpc.HttpRequest;",
		`public function GreeterRpcClient(baseUrl:String, contentType:String = "application/proto", headers:Array = null, transport:HttpTransport = null)`,
		"super(baseUrl, contentType, headers, transport);",
		"public function sayHello(request:test.v1.HelloRequest, onComplete:Function, onError:Function, timeoutMilliseconds:uint = 0):HttpRequest",
		"request:test.v1.HelloRequest,",
		"const buffer:ByteArray = BufferPool.acquire();",
		"test.v1.HelloRequest.serializeBytes(request, buffer);",
		`"/test.v1.Greeter/SayHello",`,
		"onComplete(test.v1.HelloResponse.deserializeBytes(responseBytes));",
		"timeoutMilliseconds",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated service missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileIntegerKindsUseCorrectCodecs(t *testing.T) {
	plugin := integerKindsPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	wantParts := []string{
		"dst.int32Value = Deserialize.readInt32(src);",
		"dst.uint32Value = Deserialize.readVarint32(src);",
		"dst.sint32Value = Deserialize.readSint32(src);",
		"dst.fixed32Value = src.readUnsignedInt();",
		"dst.sfixed32Value = src.readInt();",
		"Deserialize.readVarint64s(src, dst.int64Value);",
		"Deserialize.readVarint64(src, dst.uint64Value);",
		"Deserialize.readSint64(src, dst.sint64Value);",
		"Deserialize.readFixed64(src, dst.fixed64Value);",
		"Deserialize.readSfixed64(src, dst.sfixed64Value);",
		"Serialize.writeInt32(dst, localInt32Value);",
		"Serialize.writeVarint32(dst, localUint32Value);",
		"Serialize.writeSint32(dst, localSint32Value);",
		"dst.writeUnsignedInt(localFixed32Value);",
		"dst.writeInt(localSfixed32Value);",
		"Serialize.writeVarint64s(dst, localInt64Value.low, localInt64Value.high);",
		"Serialize.writeVarint64(dst, localUint64Value.low, localUint64Value.high);",
		"Serialize.writeSint64(dst, localSint64Value.low, localSint64Value.high);",
		"dst.writeUnsignedInt(localFixed64Value.low);",
		"dst.writeInt(localSfixed64Value.high);",
		"Deserialize.readInt32Vector(src, dst.int32Values);",
		"Deserialize.readVarint32Vector(src, dst.uint32Values);",
		"Deserialize.readSint32Vector(src, dst.sint32Values);",
		"Deserialize.readFixed32Vector(src, dst.fixed32Values);",
		"Deserialize.readFixed32sVector(src, dst.sfixed32Values);",
		"Deserialize.readVarint64sVector(src, dst.int64Values);",
		"Deserialize.readVarint64Vector(src, dst.uint64Values);",
		"Deserialize.readSint64Vector(src, dst.sint64Values);",
		"Deserialize.readFixed64Vector(src, dst.fixed64Values);",
		"Deserialize.readFixed64sVector(src, dst.sfixed64Values);",
		"Serialize.writeInt32Vector(dst, localInt32Values, reuseBuffer, vecLength);",
		"Serialize.writeVarint32Vector(dst, localUint32Values, reuseBuffer, vecLength);",
		"Serialize.writeSint32Vector(dst, localSint32Values, reuseBuffer, vecLength);",
		"Serialize.writeFixed32Vector(dst, localFixed32Values, vecLength);",
		"Serialize.writeSfixed32Vector(dst, localSfixed32Values, vecLength);",
		"Serialize.writeVarint64sVector(dst, localInt64Values, reuseBuffer, vecLength);",
		"Serialize.writeVarint64Vector(dst, localUint64Values, reuseBuffer, vecLength);",
		"Serialize.writeSint64Vector(dst, localSint64Values, reuseBuffer, vecLength);",
		"Serialize.writeFixed64Vector(dst, localFixed64Values, vecLength);",
		"Serialize.writeSfixed64Vector(dst, localSfixed64Values, vecLength);",
		"dst.int64Values.copyFrom(src.int64Values);",
		"dst.uint64Values.copyFrom(src.uint64Values);",
		"dst.sint64Values.copyFrom(src.sint64Values);",
		"dst.fixed64Values.copyFrom(src.fixed64Values);",
		"dst.sfixed64Values.copyFrom(src.sfixed64Values);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated integer message missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileRejectsStreamingServices(t *testing.T) {
	tests := []struct {
		name            string
		clientStreaming bool
		serverStreaming bool
		wantKind        string
	}{
		{name: "client", clientStreaming: true, wantKind: "client-streaming"},
		{name: "server", serverStreaming: true, wantKind: "server-streaming"},
		{name: "bidirectional", clientStreaming: true, serverStreaming: true, wantKind: "bidirectional-streaming"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			plugin := streamingServicePlugin(t, tt.clientStreaming, tt.serverStreaming)
			generator := internal.NewGenerator(plugin, internal.Options{})

			err := generator.GenerateFile(plugin.Files[0])
			if err == nil {
				t.Fatal("GenerateFile() error = nil, want streaming RPC rejection")
			}
			if !strings.Contains(err.Error(), "RPC method test.v1.Greeter.SayHello is "+tt.wantKind) {
				t.Fatalf("GenerateFile() error = %q, want %s rejection", err, tt.wantKind)
			}
			if files := plugin.Response().GetFile(); len(files) != 0 {
				t.Fatalf("GenerateFile() generated %d files before rejecting streaming RPC", len(files))
			}
		})
	}
}

func TestGenerateFileRejectsOutputFileCollision(t *testing.T) {
	plugin := fileCollisionPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	err := generator.GenerateFile(plugin.Files[0])
	if err == nil {
		t.Fatal("GenerateFile() error = nil, want file collision")
	}
	if !strings.Contains(err.Error(), "collides") {
		t.Fatalf("GenerateFile() error = %q, want collision", err)
	}
}

func TestGenerateFileEditionsDefaults(t *testing.T) {
	plugin := editionsDefaultsPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	files := plugin.Response().GetFile()
	if len(files) != 1 {
		t.Fatalf("generated %d files, want 1", len(files))
	}

	content := files[0].GetContent()
	wantParts := []string{
		"public static const DEFAULT_ENABLED:Boolean = true;",
		"public static const DEFAULT_SPEED:int = 42;",
		`public static const DEFAULT_TITLE:String = "hi \"there\"\n";`,
		"public static const DEFAULT_RATIO:Number = Number.POSITIVE_INFINITY;",
		"public static const DEFAULT_BIG:Int64 = new Int64(4294967295, -1);",
		"public static const DEFAULT_BLOB:ByteArray = makeDefaultBlob();",
		"private static function makeDefaultBlob():ByteArray",
		// Invalid UTF-8 defaults fall back to byte-at-a-time building.
		"bytes.writeByte(1);",
		"bytes.writeByte(255);",
		// Valid UTF-8 defaults round-trip through one writeUTFBytes call.
		"bytes.writeUTFBytes(\"hi \\u0001\");",
		// Presence representation is unchanged: unset stays null.
		"public var enabled:OptionalBoolean = null;",
	}
	for _, part := range wantParts {
		if !strings.Contains(content, part) {
			t.Errorf("generated content missing %q", part)
		}
	}
}

func TestGenerateFileEditionsCustomOptionsAllowed(t *testing.T) {
	plugin := editionsExtensionPlugin(t, ".google.protobuf.FieldOptions")
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[1]); err != nil {
		t.Fatalf("GenerateFile() error = %v, want custom options accepted", err)
	}
	files := plugin.Response().GetFile()
	if len(files) != 1 {
		t.Fatalf("generated %d files, want 1", len(files))
	}
	if got, want := files[0].GetName(), "test/v1/Example.as"; got != want {
		t.Fatalf("generated file name = %q, want %q", got, want)
	}
}

func TestGenerateFileEditionsMessageExtensionsRejected(t *testing.T) {
	plugin := editionsExtensionPlugin(t, ".test.v1.Example")
	generator := internal.NewGenerator(plugin, internal.Options{})

	err := generator.GenerateFile(plugin.Files[1])
	if err == nil {
		t.Fatal("GenerateFile() error = nil, want extension rejection")
	}
	if !strings.Contains(err.Error(), "extensions are not supported") {
		t.Fatalf("GenerateFile() error = %q, want extension rejection", err)
	}
}

// editionsExtensionPlugin builds an editions file declaring one extension
// of extendee; extending Example itself also gives Example an extension
// range so the descriptor stays valid.
func editionsExtensionPlugin(t *testing.T, extendee string) *protogen.Plugin {
	t.Helper()

	message := &descriptorpb.DescriptorProto{
		Name: proto.String("Example"),
		Field: []*descriptorpb.FieldDescriptorProto{{
			Name:   proto.String("x"),
			Number: proto.Int32(1),
			Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
			Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
		}},
	}
	if extendee != ".google.protobuf.FieldOptions" {
		message.ExtensionRange = []*descriptorpb.DescriptorProto_ExtensionRange{{
			Start: proto.Int32(50000),
			End:   proto.Int32(50002),
		}}
	}

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{
			protodesc.ToFileDescriptorProto(descriptorpb.File_google_protobuf_descriptor_proto),
			{
				Name:       proto.String("test.proto"),
				Syntax:     proto.String("editions"),
				Edition:    descriptorpb.Edition_EDITION_2023.Enum(),
				Package:    proto.String("test.v1"),
				Dependency: []string{"google/protobuf/descriptor.proto"},
				Options: &descriptorpb.FileOptions{
					GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
				},
				MessageType: []*descriptorpb.DescriptorProto{message},
				Extension: []*descriptorpb.FieldDescriptorProto{{
					Name:     proto.String("tag"),
					Number:   proto.Int32(50000),
					Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
					Type:     descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
					Extendee: proto.String(extendee),
				}},
			},
		},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func editionsDefaultsPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("editions"),
			Edition: descriptorpb.Edition_EDITION_2023.Enum(),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name: proto.String("Config"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:         proto.String("enabled"),
						Number:       proto.Int32(1),
						Label:        descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:         descriptorpb.FieldDescriptorProto_TYPE_BOOL.Enum(),
						DefaultValue: proto.String("true"),
					},
					{
						Name:         proto.String("speed"),
						Number:       proto.Int32(2),
						Label:        descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:         descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
						DefaultValue: proto.String("42"),
					},
					{
						Name:         proto.String("title"),
						Number:       proto.Int32(3),
						Label:        descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:         descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						DefaultValue: proto.String("hi \"there\"\n"),
					},
					{
						Name:         proto.String("ratio"),
						Number:       proto.Int32(4),
						Label:        descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:         descriptorpb.FieldDescriptorProto_TYPE_DOUBLE.Enum(),
						DefaultValue: proto.String("inf"),
					},
					{
						Name:         proto.String("big"),
						Number:       proto.Int32(5),
						Label:        descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:         descriptorpb.FieldDescriptorProto_TYPE_INT64.Enum(),
						DefaultValue: proto.String("-1"),
					},
					{
						Name:         proto.String("blob"),
						Number:       proto.Int32(6),
						Label:        descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:         descriptorpb.FieldDescriptorProto_TYPE_BYTES.Enum(),
						DefaultValue: proto.String("\\001\\377"),
					},
					{
						Name:         proto.String("text_blob"),
						Number:       proto.Int32(7),
						Label:        descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:         descriptorpb.FieldDescriptorProto_TYPE_BYTES.Enum(),
						DefaultValue: proto.String("hi \\001"),
					},
				},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func syntaxPlugin(t *testing.T, syntax string) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String(syntax),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name: proto.String("Example"),
				Field: []*descriptorpb.FieldDescriptorProto{{
					Name:   proto.String("name"),
					Number: proto.Int32(1),
					Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
					Type:   descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
				}},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func enumPlugin(t *testing.T, generate bool) *protogen.Plugin {
	t.Helper()

	var filesToGenerate []string
	if generate {
		filesToGenerate = []string{"test.proto"}
	}

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: filesToGenerate,
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			EnumType: []*descriptorpb.EnumDescriptorProto{{
				Name: proto.String("PlayerStatus"),
				Value: []*descriptorpb.EnumValueDescriptorProto{
					{Name: proto.String("PLAYER_STATUS_UNKNOWN"), Number: proto.Int32(0)},
					{Name: proto.String("PLAYER_STATUS_ACTIVE"), Number: proto.Int32(1)},
				},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func messagePlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name: proto.String("Player"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:   proto.String("name"),
						Number: proto.Int32(1),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
					},
					{
						Name:   proto.String("raw"),
						Number: proto.Int32(2),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_BYTES.Enum(),
					},
					{
						Name:   proto.String("amount"),
						Number: proto.Int32(3),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT64.Enum(),
					},
					{
						Name:   proto.String("scores"),
						Number: proto.Int32(4),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:   proto.String("ratio"),
						Number: proto.Int32(6),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_FLOAT.Enum(),
					},
					{
						Name:       proto.String("move"),
						Number:     proto.Int32(5),
						Label:      descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:       descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(),
						TypeName:   proto.String(".test.v1.Player"),
						OneofIndex: proto.Int32(0),
					},
					{
						Name:       proto.String("choice_amount"),
						Number:     proto.Int32(7),
						Label:      descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:       descriptorpb.FieldDescriptorProto_TYPE_INT64.Enum(),
						OneofIndex: proto.Int32(0),
					},
					{
						Name:       proto.String("choice_text"),
						Number:     proto.Int32(8),
						Label:      descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:       descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						OneofIndex: proto.Int32(0),
					},
					{
						Name:       proto.String("choice_bytes"),
						Number:     proto.Int32(9),
						Label:      descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:       descriptorpb.FieldDescriptorProto_TYPE_BYTES.Enum(),
						OneofIndex: proto.Int32(0),
					},
				},
				OneofDecl: []*descriptorpb.OneofDescriptorProto{{
					Name: proto.String("action"),
				}},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func anyPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{
			protodesc.ToFileDescriptorProto(anypb.File_google_protobuf_any_proto),
			{
				Name:       proto.String("test.proto"),
				Syntax:     proto.String("proto3"),
				Package:    proto.String("test.v1"),
				Dependency: []string{"google/protobuf/any.proto"},
				Options: &descriptorpb.FileOptions{
					GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
				},
				MessageType: []*descriptorpb.DescriptorProto{{
					Name: proto.String("Envelope"),
					Field: []*descriptorpb.FieldDescriptorProto{{
						Name:     proto.String("payload"),
						Number:   proto.Int32(1),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(),
						TypeName: proto.String(".google.protobuf.Any"),
					}},
				}},
			},
		},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func optionalPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	fields := []*descriptorpb.FieldDescriptorProto{
		optionalField("count", 1, descriptorpb.FieldDescriptorProto_TYPE_INT32, 0),
		optionalField("label", 2, descriptorpb.FieldDescriptorProto_TYPE_STRING, 1),
		optionalField("total", 3, descriptorpb.FieldDescriptorProto_TYPE_UINT64, 2),
	}
	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"optional.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("optional.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{GoPackage: proto.String("example.com/test;test")},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name:  proto.String("OptionalValues"),
				Field: fields,
				OneofDecl: []*descriptorpb.OneofDescriptorProto{
					{Name: proto.String("_count")},
					{Name: proto.String("_label")},
					{Name: proto.String("_total")},
				},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func optionalField(name string, number int32, kind descriptorpb.FieldDescriptorProto_Type, oneof int32) *descriptorpb.FieldDescriptorProto {
	return &descriptorpb.FieldDescriptorProto{
		Name:           proto.String(name),
		Number:         proto.Int32(number),
		Label:          descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
		Type:           kind.Enum(),
		OneofIndex:     proto.Int32(oneof),
		Proto3Optional: proto.Bool(true),
	}
}

func highTagPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name: proto.String("HighTag"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:   proto.String("two_byte"),
						Number: proto.Int32(16),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:   proto.String("three_byte"),
						Number: proto.Int32(2048),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:   proto.String("four_byte"),
						Number: proto.Int32(262144),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:   proto.String("five_byte"),
						Number: proto.Int32(33554432),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
				},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func servicePlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: proto.String("HelloRequest")},
				{Name: proto.String("HelloResponse")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{{
				Name: proto.String("Greeter"),
				Method: []*descriptorpb.MethodDescriptorProto{{
					Name:       proto.String("SayHello"),
					InputType:  proto.String(".test.v1.HelloRequest"),
					OutputType: proto.String(".test.v1.HelloResponse"),
				}},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func integerKindsPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	names := []string{"int32", "uint32", "sint32", "fixed32", "sfixed32", "int64", "uint64", "sint64", "fixed64", "sfixed64"}
	kinds := []descriptorpb.FieldDescriptorProto_Type{
		descriptorpb.FieldDescriptorProto_TYPE_INT32,
		descriptorpb.FieldDescriptorProto_TYPE_UINT32,
		descriptorpb.FieldDescriptorProto_TYPE_SINT32,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED32,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED32,
		descriptorpb.FieldDescriptorProto_TYPE_INT64,
		descriptorpb.FieldDescriptorProto_TYPE_UINT64,
		descriptorpb.FieldDescriptorProto_TYPE_SINT64,
		descriptorpb.FieldDescriptorProto_TYPE_FIXED64,
		descriptorpb.FieldDescriptorProto_TYPE_SFIXED64,
	}
	fields := make([]*descriptorpb.FieldDescriptorProto, 0, len(kinds)*2)
	for i, kind := range kinds {
		fields = append(fields, &descriptorpb.FieldDescriptorProto{
			Name:   proto.String(names[i] + "_value"),
			Number: proto.Int32(int32(i + 1)),
			Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
			Type:   kind.Enum(),
		})
		fields = append(fields, &descriptorpb.FieldDescriptorProto{
			Name:   proto.String(names[i] + "_values"),
			Number: proto.Int32(int32(i + 11)),
			Label:  descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
			Type:   kind.Enum(),
		})
	}

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"integers.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("integers.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{Name: proto.String("Integers"), Field: fields}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func streamingServicePlugin(t *testing.T, clientStreaming, serverStreaming bool) *protogen.Plugin {
	t.Helper()

	plugin := servicePlugin(t)
	method := plugin.Request.ProtoFile[0].Service[0].Method[0]
	method.ClientStreaming = proto.Bool(clientStreaming)
	method.ServerStreaming = proto.Bool(serverStreaming)

	plugin, err := protogen.Options{}.New(plugin.Request)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func fileCollisionPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{
				{
					Name: proto.String("Outer"),
					NestedType: []*descriptorpb.DescriptorProto{{
						Name: proto.String("Inner"),
					}},
				},
				{
					Name: proto.String("OuterInner"),
				},
			},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}
