package internal

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
)

func (g *Generator) generateFileHeaderComment(path string) {
	g.generateLeadingComment(protogen.Comments(fmt.Sprintf(
		"Code generated by protoc-gen-as3.\nSource: %s",
		path,
	)), false)
}

func (g *Generator) generateLeadingComment(comments protogen.Comments, trailingNewline bool) bool {
	lines := commentLines(comments)
	if len(lines) == 0 {
		return false
	}

	g.w.Line("/**")
	for _, line := range lines {
		if line == "" {
			g.w.Line(" *")
		} else {
			g.w.Line(" * %s", line)
		}
	}
	g.w.Line(" */")
	if trailingNewline {
		g.w.BlankLine()
	}
	return true
}

func (g *Generator) generateTrailingComment(indentFirstLine bool, comments protogen.Comments) bool {
	comment := strings.TrimRightFunc(comments.String(), unicode.IsSpace)
	if comment == "" {
		return false
	}

	lines := strings.Split(comment, "\n")
	line := strings.TrimSpace(lines[0])
	line = strings.TrimSpace(strings.TrimPrefix(line, "//"))
	if line == "" {
		return false
	}

	if indentFirstLine {
		g.w.WriteIndent()
	} else {
		g.w.Write(" ")
	}
	g.w.Write("// %s", line)
	return true
}

func commentLines(comments protogen.Comments) []string {
	raw := strings.TrimRightFunc(string(comments), unicode.IsSpace)
	if raw == "" {
		return nil
	}

	lines := strings.Split(raw, "\n")
	for i, line := range lines {
		line = strings.TrimRightFunc(line, unicode.IsSpace)
		// protoc preserves the space between a line-comment marker and its
		// contents. Remove that padding while retaining intentional indentation.
		line = strings.TrimPrefix(line, " ")
		lines[i] = line
	}
	return lines
}
