package internal

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

func (g *Generator) generateEnumFile(enum *protogen.Enum) error {
	filename, file, err := g.newGeneratedFile(string(enum.Desc.ParentFile().Package()), EnumClassName(enum))
	if err != nil {
		return err
	}
	g.w.Reset(file)

	if err := g.generateEnumClass(enum); err != nil {
		return err
	}
	if err := g.w.Err(); err != nil {
		return err
	}

	g.log.Debug("generated enum file", "path", filename)
	return nil
}

func (g *Generator) generateEnumClass(enum *protogen.Enum) error {
	packageName := string(enum.Desc.ParentFile().Package())

	g.generateLeadingComment(protogen.Comments(fmt.Sprintf(
		"Code generated by protoc-gen-as3.\nSource: %s",
		enum.Desc.ParentFile().Path(),
	)), false)
	g.w.Line("package %s", packageName)
	g.w.Line("{")
	g.w.Indent()

	g.generateLeadingComment(enum.Comments.Leading, true)
	g.w.Line("public final class %s", EnumClassName(enum))
	g.w.Line("{")
	g.w.Indent()

	if g.generateTrailingComment(true, enum.Comments.Trailing) {
		g.w.BlankLine()
	}
	g.generateEnumFields(enum)

	g.w.Dedent()
	g.w.Line("}")
	g.w.Dedent()
	g.w.Line("}")
	return nil
}

func (g *Generator) generateEnumFields(enum *protogen.Enum) {
	for i, value := range enum.Values {
		if value.Comments.Leading != "" && i > 0 {
			g.w.BlankLine()
		}
		g.generateLeadingComment(value.Comments.Leading, false)
		g.w.WriteIndent()
		g.w.Write("public static const %s:uint = %d;", EnumName(value), value.Desc.Number())
		g.generateTrailingComment(false, value.Comments.Trailing)
		g.w.Write("\n")
	}
}
