package internal_test

import (
	"strings"
	"testing"

	"github.com/33TU/as3pb/internal"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/known/anypb"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestGenerateFileEnum(t *testing.T) {
	plugin := enumPlugin(t, true)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	files := plugin.Response().GetFile()
	if len(files) != 1 {
		t.Fatalf("generated %d files, want 1", len(files))
	}
	if got, want := files[0].GetName(), "test/v1/PlayerStatus.as"; got != want {
		t.Fatalf("generated file name = %q, want %q", got, want)
	}

	want := `/**
 * Code generated by protoc-gen-as3.
 * Source: test.proto
 */
package test.v1
{
    public final class PlayerStatus
    {
        public static const PLAYER_STATUS_UNKNOWN:uint = 0;
        public static const PLAYER_STATUS_ACTIVE:uint = 1;
    }
}
`
	if got := files[0].GetContent(); got != want {
		t.Fatalf("generated content:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateFileSkipsNonGeneratedFile(t *testing.T) {
	plugin := enumPlugin(t, false)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}
	if got := len(plugin.Response().GetFile()); got != 0 {
		t.Fatalf("generated %d files, want 0", got)
	}
}

func TestGenerateFileRejectsProto2(t *testing.T) {
	plugin := syntaxPlugin(t, "proto2")
	generator := internal.NewGenerator(plugin, internal.Options{})

	err := generator.GenerateFile(plugin.Files[0])
	if err == nil {
		t.Fatal("GenerateFile() error = nil, want proto2 rejection")
	}
	if !strings.Contains(err.Error(), "only proto3 files are supported") {
		t.Fatalf("GenerateFile() error = %q, want proto3 rejection", err)
	}
}

func TestGenerateFileMessageFieldsAndReset(t *testing.T) {
	plugin := messagePlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	files := plugin.Response().GetFile()
	if len(files) != 1 {
		t.Fatalf("generated %d files, want 1", len(files))
	}
	if got, want := files[0].GetName(), "test/v1/Player.as"; got != want {
		t.Fatalf("generated file name = %q, want %q", got, want)
	}

	content := files[0].GetContent()
	wantParts := []string{
		"import flash.utils.ByteArray;",
		"import as3pb.proto.Deserialize;",
		"import as3pb.proto.Serialize;",
		"import as3pb.proto.Buffers;",
		"import as3pb.types.Int64;",
		"import as3pb.types.AnyRegistry;",
		`public static const TYPE_URL:String = "type.googleapis.com/test.v1.Player";`,
		"public static const FIELD_MOVE:uint = 5;",
		"public var raw:ByteArray = Buffers.newByteArray();",
		"public static function reset(msg:Player):void",
		"msg.raw.length = 0;",
		"public static function deserializeBytes(src:ByteArray, dst:Player = null, limit:uint = 0):Player",
		"else",
		"dst.actionCase = 5;",
		"Deserialize.readInt32Vector(src, dst.scores);",
		"public static function serializeBytes(src:Player, dst:ByteArray):void",
		"const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;",
		"Serialize.writeInt32Vector(dst, localScores, reuseBuffer, vecLength);",
		"switch (src.actionCase)",
		"AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated content missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileCanDisableInlineReset(t *testing.T) {
	plugin := messagePlugin(t)
	inlineReset := false
	generator := internal.NewGenerator(plugin, internal.Options{InlineReset: &inlineReset})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "[Inline]") {
		t.Fatalf("generated content contains [Inline]:\n%s", content)
	}
	if !strings.Contains(content, "public static function reset(msg:Player):void") {
		t.Fatalf("generated content missing reset method:\n%s", content)
	}
}

func TestGenerateFileCanDisableSerialize(t *testing.T) {
	plugin := messagePlugin(t)
	generateSerialize := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateSerialize: &generateSerialize})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "public static function serializeBytes") {
		t.Fatalf("generated content contains serializeBytes:\n%s", content)
	}
	if strings.Contains(content, "import as3pb.proto.Serialize;") {
		t.Fatalf("generated content contains Serialize import:\n%s", content)
	}
	if !strings.Contains(content, "public static function deserializeBytes") {
		t.Fatalf("generated content missing deserializeBytes:\n%s", content)
	}
}

func TestGenerateFileCanDisableDeserialize(t *testing.T) {
	plugin := messagePlugin(t)
	generateDeserialize := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateDeserialize: &generateDeserialize})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "public static function deserializeBytes") {
		t.Fatalf("generated content contains deserializeBytes:\n%s", content)
	}
	if strings.Contains(content, "import as3pb.proto.Deserialize;") {
		t.Fatalf("generated content contains Deserialize import:\n%s", content)
	}
	if !strings.Contains(content, "public static function serializeBytes") {
		t.Fatalf("generated content missing serializeBytes:\n%s", content)
	}
}

func TestGenerateFileMapsProtobufAnyToRuntimeType(t *testing.T) {
	plugin := anyPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[1]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	wantParts := []string{
		"import as3pb.types.Any;",
		"public var payload:Any = null;",
		"dst.payload = Any.deserializeBytes(",
		"Any.serializeBytes(localPayload, messageReuseBuffer);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated Any field missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileCanDisableAnyRegistration(t *testing.T) {
	plugin := anyPlugin(t)
	generateAny := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateAny: &generateAny})

	if err := generator.GenerateFile(plugin.Files[1]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	if strings.Contains(content, "TYPE_URL") {
		t.Fatalf("generated content contains TYPE_URL:\n%s", content)
	}
	if strings.Contains(content, "AnyRegistry") {
		t.Fatalf("generated content contains AnyRegistry:\n%s", content)
	}
	if !strings.Contains(content, "import as3pb.types.Any;") {
		t.Fatalf("generated content missing Any field support:\n%s", content)
	}
}

func TestGenerateFileRejectsServicesWhenCodecsDisabled(t *testing.T) {
	plugin := servicePlugin(t)
	generateSerialize := false
	generator := internal.NewGenerator(plugin, internal.Options{GenerateSerialize: &generateSerialize})

	err := generator.GenerateFile(plugin.Files[0])
	if err == nil {
		t.Fatal("GenerateFile() error = nil, want service codec rejection")
	}
	if !strings.Contains(err.Error(), "services require serialize and deserialize") {
		t.Fatalf("GenerateFile() error = %q, want service codec rejection", err)
	}
}

func TestGenerateWriteTagUsesConstantFastPaths(t *testing.T) {
	plugin := highTagPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	content := plugin.Response().GetFile()[0].GetContent()
	wantParts := []string{
		"dst.writeShort(384);",
		"dst.writeByte(128);",
		"dst.writeShort(32896);",
		"dst.writeShort(32896);",
		"dst.writeShort(32896);",
		"dst.writeByte(1);",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated content missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileService(t *testing.T) {
	plugin := servicePlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	if err := generator.GenerateFile(plugin.Files[0]); err != nil {
		t.Fatalf("GenerateFile() error = %v", err)
	}

	var content string
	for _, file := range plugin.Response().GetFile() {
		if file.GetName() == "test/v1/GreeterRpcClient.as" {
			content = file.GetContent()
			break
		}
	}
	if content == "" {
		t.Fatalf("missing generated GreeterRpcClient.as; files: %v", plugin.Response().GetFile())
	}

	wantParts := []string{
		"public final class GreeterRpcClient extends RpcClient",
		`public function GreeterRpcClient(baseUrl:String, contentType:String = "application/proto", headers:Array = null, transport:HttpTransport = null)`,
		"super(baseUrl, contentType, headers, transport);",
		"public function sayHello(",
		"request:HelloRequest,",
		"const buffer:ByteArray = BufferPool.acquire();",
		"HelloRequest.serializeBytes(request, buffer);",
		`"/test.v1.Greeter/SayHello",`,
		"onComplete(HelloResponse.deserializeBytes(responseBytes));",
	}
	for _, want := range wantParts {
		if !strings.Contains(content, want) {
			t.Fatalf("generated service missing %q:\n%s", want, content)
		}
	}
}

func TestGenerateFileRejectsOutputFileCollision(t *testing.T) {
	plugin := fileCollisionPlugin(t)
	generator := internal.NewGenerator(plugin, internal.Options{})

	err := generator.GenerateFile(plugin.Files[0])
	if err == nil {
		t.Fatal("GenerateFile() error = nil, want file collision")
	}
	if !strings.Contains(err.Error(), "collides") {
		t.Fatalf("GenerateFile() error = %q, want collision", err)
	}
}

func syntaxPlugin(t *testing.T, syntax string) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String(syntax),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name: proto.String("Example"),
				Field: []*descriptorpb.FieldDescriptorProto{{
					Name:   proto.String("name"),
					Number: proto.Int32(1),
					Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
					Type:   descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
				}},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func enumPlugin(t *testing.T, generate bool) *protogen.Plugin {
	t.Helper()

	var filesToGenerate []string
	if generate {
		filesToGenerate = []string{"test.proto"}
	}

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: filesToGenerate,
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			EnumType: []*descriptorpb.EnumDescriptorProto{{
				Name: proto.String("PlayerStatus"),
				Value: []*descriptorpb.EnumValueDescriptorProto{
					{Name: proto.String("PLAYER_STATUS_UNKNOWN"), Number: proto.Int32(0)},
					{Name: proto.String("PLAYER_STATUS_ACTIVE"), Number: proto.Int32(1)},
				},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func messagePlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name: proto.String("Player"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:   proto.String("name"),
						Number: proto.Int32(1),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
					},
					{
						Name:   proto.String("raw"),
						Number: proto.Int32(2),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_BYTES.Enum(),
					},
					{
						Name:   proto.String("amount"),
						Number: proto.Int32(3),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT64.Enum(),
					},
					{
						Name:   proto.String("scores"),
						Number: proto.Int32(4),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:       proto.String("move"),
						Number:     proto.Int32(5),
						Label:      descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:       descriptorpb.FieldDescriptorProto_TYPE_STRING.Enum(),
						OneofIndex: proto.Int32(0),
					},
				},
				OneofDecl: []*descriptorpb.OneofDescriptorProto{{
					Name: proto.String("action"),
				}},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func anyPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{
			protodesc.ToFileDescriptorProto(anypb.File_google_protobuf_any_proto),
			{
				Name:       proto.String("test.proto"),
				Syntax:     proto.String("proto3"),
				Package:    proto.String("test.v1"),
				Dependency: []string{"google/protobuf/any.proto"},
				Options: &descriptorpb.FileOptions{
					GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
				},
				MessageType: []*descriptorpb.DescriptorProto{{
					Name: proto.String("Envelope"),
					Field: []*descriptorpb.FieldDescriptorProto{{
						Name:     proto.String("payload"),
						Number:   proto.Int32(1),
						Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:     descriptorpb.FieldDescriptorProto_TYPE_MESSAGE.Enum(),
						TypeName: proto.String(".google.protobuf.Any"),
					}},
				}},
			},
		},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func highTagPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{{
				Name: proto.String("HighTag"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{
						Name:   proto.String("two_byte"),
						Number: proto.Int32(16),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:   proto.String("three_byte"),
						Number: proto.Int32(2048),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:   proto.String("four_byte"),
						Number: proto.Int32(262144),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
					{
						Name:   proto.String("five_byte"),
						Number: proto.Int32(33554432),
						Label:  descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
						Type:   descriptorpb.FieldDescriptorProto_TYPE_INT32.Enum(),
					},
				},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func servicePlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{
				{Name: proto.String("HelloRequest")},
				{Name: proto.String("HelloResponse")},
			},
			Service: []*descriptorpb.ServiceDescriptorProto{{
				Name: proto.String("Greeter"),
				Method: []*descriptorpb.MethodDescriptorProto{{
					Name:       proto.String("SayHello"),
					InputType:  proto.String(".test.v1.HelloRequest"),
					OutputType: proto.String(".test.v1.HelloResponse"),
				}},
			}},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}

func fileCollisionPlugin(t *testing.T) *protogen.Plugin {
	t.Helper()

	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{"test.proto"},
		ProtoFile: []*descriptorpb.FileDescriptorProto{{
			Name:    proto.String("test.proto"),
			Syntax:  proto.String("proto3"),
			Package: proto.String("test.v1"),
			Options: &descriptorpb.FileOptions{
				GoPackage: proto.String("github.com/33TU/as3pb/internal/generatetest;generatetest"),
			},
			MessageType: []*descriptorpb.DescriptorProto{
				{
					Name: proto.String("Outer"),
					NestedType: []*descriptorpb.DescriptorProto{{
						Name: proto.String("Inner"),
					}},
				},
				{
					Name: proto.String("OuterInner"),
				},
			},
		}},
	}

	plugin, err := protogen.Options{}.New(req)
	if err != nil {
		t.Fatalf("protogen plugin: %v", err)
	}
	return plugin
}
