/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/api.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Api is a light-weight descriptor for an API Interface.
     *
     * Interfaces are also described as "protocol buffer services" in some contexts,
     * such as by the "service" keyword in a .proto file, but they are different
     * from API Services, which represent a concrete implementation of an interface
     * as opposed to simply a description of methods and bindings. They are also
     * sometimes simply referred to as "APIs" in other contexts, such as the name of
     * this message itself. See https://cloud.google.com/apis/design/glossary for
     * detailed terminology.
     */
    public final class Api
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Api";

        /**
         * The fully qualified name of this interface, including package name
         * followed by the interface's simple name.
         */
        public var name:String = "";

        /**
         * The methods of this interface, in unspecified order.
         */
        public var methods:Vector.<Method> = new Vector.<Method>();

        /**
         * Any metadata attached to the interface.
         */
        public var options:Vector.<Option> = new Vector.<Option>();

        /**
         * A version string for this interface. If specified, must have the form
         * `major-version.minor-version`, as in `1.10`. If the minor version is
         * omitted, it defaults to zero. If the entire version field is empty, the
         * major version is derived from the package name, as outlined below. If the
         * field is not empty, the version in the package name will be verified to be
         * consistent with what is provided here.
         *
         * The versioning schema uses [semantic
         * versioning](http://semver.org) where the major version number
         * indicates a breaking change and the minor version an additive,
         * non-breaking change. Both version numbers are signals to users
         * what to expect from different versions, and should be carefully
         * chosen based on the product plan.
         *
         * The major version is also reflected in the package name of the
         * interface, which must end in `v<major-version>`, as in
         * `google.feature.v1`. For major versions 0 and 1, the suffix can
         * be omitted. Zero major versions must only be used for
         * experimental, non-GA interfaces.
         */
        public var version:String = "";

        /**
         * Source context for the protocol buffer service represented by this
         * message.
         */
        public var sourceContext:SourceContext = null;

        /**
         * Included interfaces. See [Mixin][].
         */
        public var mixins:Vector.<Mixin> = new Vector.<Mixin>();

        /**
         * The source syntax of the service.
         */
        public var syntax:int = 0;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Api):void
        {
            msg.name = "";
            msg.methods.length = 0;
            msg.options.length = 0;
            msg.version = "";
            msg.sourceContext = null;
            msg.mixins.length = 0;
            msg.syntax = 0;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:Api):Api
        {
            if (!src)
                return null;

            const dst:Api = new Api();
            dst.name = src.name;
            const cloneSource1:Vector.<Method> = src.methods;
            const cloneTarget1:Vector.<Method> = dst.methods;
            cloneTarget1.length = cloneSource1.length;
            for (var cloneIndex1:uint = 0; cloneIndex1 < cloneSource1.length; cloneIndex1++)
                cloneTarget1[cloneIndex1] = Method.clone(cloneSource1[cloneIndex1]);
            const cloneSource2:Vector.<Option> = src.options;
            const cloneTarget2:Vector.<Option> = dst.options;
            cloneTarget2.length = cloneSource2.length;
            for (var cloneIndex2:uint = 0; cloneIndex2 < cloneSource2.length; cloneIndex2++)
                cloneTarget2[cloneIndex2] = Option.clone(cloneSource2[cloneIndex2]);
            dst.version = src.version;
            dst.sourceContext = SourceContext.clone(src.sourceContext);
            const cloneSource5:Vector.<Mixin> = src.mixins;
            const cloneTarget5:Vector.<Mixin> = dst.mixins;
            cloneTarget5.length = cloneSource5.length;
            for (var cloneIndex5:uint = 0; cloneIndex5 < cloneSource5.length; cloneIndex5++)
                cloneTarget5[cloneIndex5] = Mixin.clone(cloneSource5[cloneIndex5]);
            dst.syntax = src.syntax;

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Api = null, limit:uint = 0, reset:Boolean = true):Api
        {
            if (!dst)
                dst = new Api();
            else if (reset)
                Api.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        const msgMethods:Method = new Method();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Method.deserializeBytes(src, msgMethods, src.position + messageLength);
                        dst.methods.push(msgMethods);
                        break;
                    }
                    case 26:
                    {
                        const msgOptions:Option = new Option();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Option.deserializeBytes(src, msgOptions, src.position + messageLength);
                        dst.options.push(msgOptions);
                        break;
                    }
                    case 34:
                    {
                        dst.version = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 42:
                    {
                        messageLength = Deserialize.readVarint32(src);
                        dst.sourceContext = SourceContext.deserializeBytes(src, dst.sourceContext, src.position + messageLength, false);
                        break;
                    }
                    case 50:
                    {
                        const msgMixins:Mixin = new Mixin();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Mixin.deserializeBytes(src, msgMixins, src.position + messageLength);
                        dst.mixins.push(msgMixins);
                        break;
                    }
                    case 56:
                    {
                        dst.syntax = Deserialize.readInt32(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Api, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localMethods:Vector.<Method> = src.methods;
            const localOptions:Vector.<Option> = src.options;
            const localVersion:String = src.version;
            const localSourceContext:SourceContext = src.sourceContext;
            const localMixins:Vector.<Mixin> = src.mixins;
            const localSyntax:int = src.syntax;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if ((vecLength = localMethods.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(18);
                        messageReuseBuffer.length = 0;
                        Method.serializeBytes(localMethods[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if ((vecLength = localOptions.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(26);
                        messageReuseBuffer.length = 0;
                        Option.serializeBytes(localOptions[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if (localVersion)
                {
                    dst.writeByte(34);
                    Serialize.writeString(dst, localVersion, reuseBuffer);
                }
                if (localSourceContext)
                {
                    dst.writeByte(42);
                    messageReuseBuffer.length = 0;
                    SourceContext.serializeBytes(localSourceContext, messageReuseBuffer);
                    Serialize.writeVarint32(dst, messageReuseBuffer.length);
                    dst.writeBytes(messageReuseBuffer);
                }
                if ((vecLength = localMixins.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(50);
                        messageReuseBuffer.length = 0;
                        Mixin.serializeBytes(localMixins[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if (localSyntax)
                {
                    dst.writeByte(56);
                    Serialize.writeInt32(dst, localSyntax);
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
