/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/wrappers.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Wrapper message for `bool`.
     *
     * The JSON representation for `BoolValue` is JSON `true` and `false`.
     */
    public final class BoolValue
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.BoolValue";

        /**
         * The bool value.
         */
        public var value:Boolean = false;

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.BoolValue):void
        {
            msg.value = false;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.BoolValue):google.protobuf.BoolValue
        {
            if (!src)
                return null;

            const dst:google.protobuf.BoolValue = new google.protobuf.BoolValue();
            dst.value = src.value;
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.BoolValue = null, limit:uint = 0, reset:Boolean = true):google.protobuf.BoolValue
        {
            if (!dst)
                dst = new google.protobuf.BoolValue();
            else if (reset)
                google.protobuf.BoolValue.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 8:
                    {
                        dst.value = Deserialize.readBool(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();

                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.BoolValue, dst:ByteArray):void
        {
            if (!src)
                return;

            const localValue:Boolean = src.value;

            if (localValue)
            {
                dst.writeByte(8);
                dst.writeByte(localValue ? 1 : 0);
            }

            if (src.unknownFields)
                dst.writeBytes(src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
