/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/wrappers.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Pack;
    import as3pb.proto.PackContext;
    import as3pb.proto.Unpack;
    import as3pb.proto.UnpackContext;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Wrapper message for `bytes`.
     *
     * The JSON representation for `BytesValue` is JSON string.
     */
    public final class BytesValue
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.BytesValue";

        /**
         * The bytes value.
         */
        public var value:ByteArray = Buffers.newByteArray();

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.BytesValue):void
        {
            msg.value.length = 0;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.BytesValue):google.protobuf.BytesValue
        {
            if (!src)
                return null;

            const dst:google.protobuf.BytesValue = new google.protobuf.BytesValue();
            dst.value = Buffers.cloneByteArray(src.value);
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Reusable destination message, or null to allocate.
         * @param length Number of bytes to decode from the current position; zero means an empty message.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.BytesValue, length:uint, reset:Boolean = true):google.protobuf.BytesValue
        {
            if (!dst)
                dst = new google.protobuf.BytesValue();
            else if (reset)
                google.protobuf.BytesValue.reset(dst);

            if (!length)
                return dst;
            else if (length > src.bytesAvailable)
                throw new Error("Invalid protobuf message length");

            const end:uint = src.position + length;

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        Deserialize.readBytesInto(src, dst.value);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();

                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.BytesValue, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;

            const localValue:ByteArray = src.value;

            if (localValue.length)
            {
                dst.writeByte(10);
                Serialize.writeBytes(dst, localValue);
            }

            if (src.unknownFields)
                dst.writeBytes(src.unknownFields);
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The active UnpackContext; bind with Unpack.begin first.
         * @param dst Reusable destination message, or null to allocate.
         * @param length Number of bytes to decode from the current position; zero means an empty message.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeMemory(src:UnpackContext, dst:google.protobuf.BytesValue, length:uint, reset:Boolean = true):google.protobuf.BytesValue
        {
            if (!dst)
                dst = new google.protobuf.BytesValue();
            else if (reset)
                google.protobuf.BytesValue.reset(dst);

            if (!length)
                return dst;
            else if (src.position > src.limit || length > src.limit - src.position)
                throw new Error("Invalid protobuf message length");

            const end:uint = src.position + length;
            const previousLimit:uint = src.limit;
            src.limit = end;
            try
            {

                while (src.position < end)
                {
                    const tag:uint = Unpack.readTag(src);
                    switch (tag)
                    {
                        case 10:
                        {
                            Unpack.readBytesInto(src, dst.value);
                            break;
                        }
                        default:
                        {
                            if ((tag >>> 3) == 0)
                                throw new Error("Invalid protobuf field number");

                            if (dst.unknownFields == null)
                                dst.unknownFields = Buffers.newByteArray();

                            Unpack.captureUnknownField(src, tag, dst.unknownFields);
                            break;
                        }
                    }
                }

                if (src.position > end)
                    throw new Error("Truncated protobuf message");

            }
            finally
            {
                src.limit = previousLimit;
            }
            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The active PackContext; bind with Pack.begin first.
         */
        public static function serializeMemory(src:google.protobuf.BytesValue, dst:PackContext):void
        {
            if (!src)
                return;

            const localValue:ByteArray = src.value;

            if (localValue.length)
            {
                Pack.writeByte(dst, 10);
                Pack.writeBytes(dst, localValue);
            }

            if (src.unknownFields)
                Pack.writeRawBytes(dst, src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
