/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/wrappers.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Wrapper message for `bytes`.
     *
     * The JSON representation for `BytesValue` is JSON string.
     */
    public final class BytesValue
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.BytesValue";

        /**
         * The bytes value.
         */
        public var value:ByteArray = Buffers.newByteArray();

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:BytesValue):void
        {
            msg.value.length = 0;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:BytesValue):BytesValue
        {
            if (!src)
                return null;

            const dst:BytesValue = new BytesValue();
            dst.value = Buffers.cloneByteArray(src.value);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:BytesValue = null, limit:uint = 0, reset:Boolean = true):BytesValue
        {
            if (!dst)
                dst = new BytesValue();
            else if (reset)
                BytesValue.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 10:
                    {
                        Deserialize.readBytesInto(src, dst.value);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:BytesValue, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;

            const localValue:ByteArray = src.value;

            if (localValue.length)
            {
                dst.writeByte(10);
                Serialize.writeBytes(dst, localValue);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
