/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/duration.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.types.Int64;
    import as3pb.wkt.AnyRegistry;

    /**
     * A Duration represents a signed, fixed-length span of time represented
     * as a count of seconds and fractions of seconds at nanosecond
     * resolution. It is independent of any calendar and concepts like "day"
     * or "month". It is related to Timestamp in that the difference between
     * two Timestamp values is a Duration and it can be added or subtracted
     * from a Timestamp. Range is approximately +-10,000 years.
     *
     * # Examples
     *
     * Example 1: Compute Duration from two Timestamps in pseudo code.
     *
     *     Timestamp start = ...;
     *     Timestamp end = ...;
     *     Duration duration = ...;
     *
     *     duration.seconds = end.seconds - start.seconds;
     *     duration.nanos = end.nanos - start.nanos;
     *
     *     if (duration.seconds < 0 && duration.nanos > 0) {
     *       duration.seconds += 1;
     *       duration.nanos -= 1000000000;
     *     } else if (duration.seconds > 0 && duration.nanos < 0) {
     *       duration.seconds -= 1;
     *       duration.nanos += 1000000000;
     *     }
     *
     * Example 2: Compute Timestamp from Timestamp + Duration in pseudo code.
     *
     *     Timestamp start = ...;
     *     Duration duration = ...;
     *     Timestamp end = ...;
     *
     *     end.seconds = start.seconds + duration.seconds;
     *     end.nanos = start.nanos + duration.nanos;
     *
     *     if (end.nanos < 0) {
     *       end.seconds -= 1;
     *       end.nanos += 1000000000;
     *     } else if (end.nanos >= 1000000000) {
     *       end.seconds += 1;
     *       end.nanos -= 1000000000;
     *     }
     *
     * Example 3: Compute Duration from datetime.timedelta in Python.
     *
     *     td = datetime.timedelta(days=3, minutes=10)
     *     duration = Duration()
     *     duration.FromTimedelta(td)
     *
     * # JSON Mapping
     *
     * In JSON format, the Duration type is encoded as a string rather than an
     * object, where the string ends in the suffix "s" (indicating seconds) and
     * is preceded by the number of seconds, with nanoseconds expressed as
     * fractional seconds. For example, 3 seconds with 0 nanoseconds should be
     * encoded in JSON format as "3s", while 3 seconds and 1 nanosecond should
     * be expressed in JSON format as "3.000000001s", and 3 seconds and 1
     * microsecond should be expressed in JSON format as "3.000001s".
     */
    public final class Duration
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Duration";

        /**
         * Signed seconds of the span of time. Must be from -315,576,000,000
         * to +315,576,000,000 inclusive. Note: these bounds are computed from:
         * 60 sec/min * 60 min/hr * 24 hr/day * 365.25 days/year * 10000 years
         */
        public var seconds:Int64 = new Int64();

        /**
         * Signed fractions of a second at nanosecond resolution of the span
         * of time. Durations less than one second are represented with a 0
         * `seconds` field and a positive or negative `nanos` field. For durations
         * of one second or more, a non-zero value for the `nanos` field must be
         * of the same sign as the `seconds` field. Must be from -999,999,999
         * to +999,999,999 inclusive.
         */
        public var nanos:int = 0;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Duration):void
        {
            msg.seconds.low = 0;
            msg.seconds.high = 0;
            msg.nanos = 0;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:Duration):Duration
        {
            if (!src)
                return null;

            const dst:Duration = new Duration();
            dst.seconds.copyFrom(src.seconds);
            dst.nanos = src.nanos;

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Duration = null, limit:uint = 0, reset:Boolean = true):Duration
        {
            if (!dst)
                dst = new Duration();
            else if (reset)
                Duration.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 8:
                    {
                        Deserialize.readVarint64s(src, dst.seconds);
                        break;
                    }
                    case 16:
                    {
                        dst.nanos = Deserialize.readInt32(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Duration, dst:ByteArray):void
        {
            if (!src)
                return;

            const localSeconds:Int64 = src.seconds;
            const localNanos:int = src.nanos;

            if (localSeconds.low || localSeconds.high)
            {
                dst.writeByte(8);
                Serialize.writeVarint64s(dst, localSeconds.low, localSeconds.high);
            }
            if (localNanos)
            {
                dst.writeByte(16);
                Serialize.writeInt32(dst, localNanos);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
