/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import flash.errors.EOFError;
    import as3pb.proto.Unpack;
    import as3pb.proto.UnpackContext;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Enum value definition.
     */
    public final class EnumValue
    {
        private static const UNPACK:UnpackContext = new UnpackContext();
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.EnumValue";

        /**
         * Enum value name.
         */
        public var name:String = "";

        /**
         * Enum value number.
         */
        public var number:int = 0;

        /**
         * Protocol buffer options.
         */
        public var options:Vector.<google.protobuf.Option> = new Vector.<google.protobuf.Option>();

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.EnumValue):void
        {
            msg.name = "";
            msg.number = 0;
            msg.options.length = 0;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.EnumValue):google.protobuf.EnumValue
        {
            if (!src)
                return null;

            const dst:google.protobuf.EnumValue = new google.protobuf.EnumValue();
            dst.name = src.name;
            dst.number = src.number;
            const cloneSource2:Vector.<google.protobuf.Option> = src.options;
            const cloneTarget2:Vector.<google.protobuf.Option> = dst.options;
            cloneTarget2.length = cloneSource2.length;
            for (var cloneIndex2:uint = 0; cloneIndex2 < cloneSource2.length; cloneIndex2++)
                cloneTarget2[cloneIndex2] = google.protobuf.Option.clone(cloneSource2[cloneIndex2]);
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.EnumValue = null, limit:uint = 0, reset:Boolean = true):google.protobuf.EnumValue
        {
            const context:UnpackContext = UNPACK;
            Unpack.begin(context, src, limit);
            try
            {
                dst = deserializeMemory(context, dst, context.limit, reset);
            }
            finally
            {
                Unpack.end(context);
            }
            return dst;
        }

        /** Decode within an active memory binding; nested messages share the context. */
        public static function deserializeMemory(src:UnpackContext, dst:google.protobuf.EnumValue = null, limit:uint = 0, reset:Boolean = true):google.protobuf.EnumValue
        {
            if (!dst)
                dst = new google.protobuf.EnumValue();
            else if (reset)
                google.protobuf.EnumValue.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.limit;

            if (end < src.position || end > src.limit)
                throw new Error("Invalid protobuf message limit");

            const previousLimit:uint = src.limit;
            src.limit = end;
            try
            {
                while (src.position < end)
                {
                    const tag:uint = Unpack.readTag(src);
                    switch (tag)
                    {
                        case 10:
                        {
                            dst.name = Unpack.readString(src);
                            break;
                        }
                        case 16:
                        {
                            dst.number = Unpack.readInt32(src);
                            break;
                        }
                        case 26:
                        {
                            const msgOptions:google.protobuf.Option = new google.protobuf.Option();
                            messageLength = Unpack.readVarint32(src);
                            if (src.position > src.limit || messageLength > src.limit - src.position)
                                throw new EOFError("Truncated protobuf input");
                            if (messageLength !== 0)
                                google.protobuf.Option.deserializeMemory(src, msgOptions, src.position + messageLength);
                            dst.options.push(msgOptions);
                            break;
                        }
                        default:
                        {
                            if ((tag >>> 3) == 0)
                                throw new Error("Invalid protobuf field number");

                            if (dst.unknownFields == null)
                                dst.unknownFields = Buffers.newByteArray();

                            Unpack.captureUnknownField(src, tag, dst.unknownFields);
                            break;
                        }
                    }
                }

                if (src.position > end)
                    throw new Error("Truncated protobuf message");

            }
            finally
            {
                src.limit = previousLimit;
            }
            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.EnumValue, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localNumber:int = src.number;
            const localOptions:Vector.<google.protobuf.Option> = src.options;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if (localNumber)
                {
                    dst.writeByte(16);
                    Serialize.writeInt32(dst, localNumber);
                }
                if ((vecLength = localOptions.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(26);
                        messageReuseBuffer.length = 0;
                        google.protobuf.Option.serializeBytes(localOptions[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }

                if (src.unknownFields)
                    dst.writeBytes(src.unknownFields);
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
