/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Enum value definition.
     */
    public final class EnumValue
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.EnumValue";

        /**
         * Enum value name.
         */
        public var name:String = "";

        /**
         * Enum value number.
         */
        public var number:int = 0;

        /**
         * Protocol buffer options.
         */
        public var options:Vector.<Option> = new Vector.<Option>();

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:EnumValue):void
        {
            msg.name = "";
            msg.number = 0;
            msg.options.length = 0;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:EnumValue):EnumValue
        {
            if (!src)
                return null;

            const dst:EnumValue = new EnumValue();
            dst.name = src.name;
            dst.number = src.number;
            const cloneSource2:Vector.<Option> = src.options;
            const cloneTarget2:Vector.<Option> = dst.options;
            cloneTarget2.length = cloneSource2.length;
            for (var cloneIndex2:uint = 0; cloneIndex2 < cloneSource2.length; cloneIndex2++)
                cloneTarget2[cloneIndex2] = Option.clone(cloneSource2[cloneIndex2]);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:EnumValue = null, limit:uint = 0, reset:Boolean = true):EnumValue
        {
            if (!dst)
                dst = new EnumValue();
            else if (reset)
                EnumValue.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 16:
                    {
                        dst.number = Deserialize.readInt32(src);
                        break;
                    }
                    case 26:
                    {
                        const msgOptions:Option = new Option();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Option.deserializeBytes(src, msgOptions, src.position + messageLength);
                        dst.options.push(msgOptions);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:EnumValue, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localNumber:int = src.number;
            const localOptions:Vector.<Option> = src.options;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if (localNumber)
                {
                    dst.writeByte(16);
                    Serialize.writeInt32(dst, localNumber);
                }
                if ((vecLength = localOptions.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(26);
                        messageReuseBuffer.length = 0;
                        Option.serializeBytes(localOptions[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
