/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Enum type definition.
     */
    public final class Enum
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Enum";

        /**
         * Enum type name.
         */
        public var name:String = "";

        /**
         * Enum value definitions.
         */
        public var enumvalue:Vector.<google.protobuf.EnumValue> = new Vector.<google.protobuf.EnumValue>();

        /**
         * Protocol buffer options.
         */
        public var options:Vector.<google.protobuf.Option> = new Vector.<google.protobuf.Option>();

        /**
         * The source context.
         */
        public var sourceContext:google.protobuf.SourceContext = null;

        /**
         * The source syntax.
         */
        public var syntax:int = 0;

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.Enum):void
        {
            msg.name = "";
            msg.enumvalue.length = 0;
            msg.options.length = 0;
            msg.sourceContext = null;
            msg.syntax = 0;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.Enum):google.protobuf.Enum
        {
            if (!src)
                return null;

            const dst:google.protobuf.Enum = new google.protobuf.Enum();
            dst.name = src.name;
            const cloneSource1:Vector.<google.protobuf.EnumValue> = src.enumvalue;
            const cloneTarget1:Vector.<google.protobuf.EnumValue> = dst.enumvalue;
            cloneTarget1.length = cloneSource1.length;
            for (var cloneIndex1:uint = 0; cloneIndex1 < cloneSource1.length; cloneIndex1++)
                cloneTarget1[cloneIndex1] = google.protobuf.EnumValue.clone(cloneSource1[cloneIndex1]);
            const cloneSource2:Vector.<google.protobuf.Option> = src.options;
            const cloneTarget2:Vector.<google.protobuf.Option> = dst.options;
            cloneTarget2.length = cloneSource2.length;
            for (var cloneIndex2:uint = 0; cloneIndex2 < cloneSource2.length; cloneIndex2++)
                cloneTarget2[cloneIndex2] = google.protobuf.Option.clone(cloneSource2[cloneIndex2]);
            dst.sourceContext = google.protobuf.SourceContext.clone(src.sourceContext);
            dst.syntax = src.syntax;
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.Enum = null, limit:uint = 0, reset:Boolean = true):google.protobuf.Enum
        {
            if (!dst)
                dst = new google.protobuf.Enum();
            else if (reset)
                google.protobuf.Enum.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        const msgEnumvalue:google.protobuf.EnumValue = new google.protobuf.EnumValue();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            google.protobuf.EnumValue.deserializeBytes(src, msgEnumvalue, src.position + messageLength);
                        dst.enumvalue.push(msgEnumvalue);
                        break;
                    }
                    case 26:
                    {
                        const msgOptions:google.protobuf.Option = new google.protobuf.Option();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            google.protobuf.Option.deserializeBytes(src, msgOptions, src.position + messageLength);
                        dst.options.push(msgOptions);
                        break;
                    }
                    case 34:
                    {
                        messageLength = Deserialize.readVarint32(src);
                        dst.sourceContext = google.protobuf.SourceContext.deserializeBytes(src, dst.sourceContext, src.position + messageLength, false);
                        break;
                    }
                    case 40:
                    {
                        dst.syntax = Deserialize.readInt32(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();

                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.Enum, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localEnumvalue:Vector.<google.protobuf.EnumValue> = src.enumvalue;
            const localOptions:Vector.<google.protobuf.Option> = src.options;
            const localSourceContext:google.protobuf.SourceContext = src.sourceContext;
            const localSyntax:int = src.syntax;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if ((vecLength = localEnumvalue.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(18);
                        messageReuseBuffer.length = 0;
                        google.protobuf.EnumValue.serializeBytes(localEnumvalue[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if ((vecLength = localOptions.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(26);
                        messageReuseBuffer.length = 0;
                        google.protobuf.Option.serializeBytes(localOptions[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if (localSourceContext)
                {
                    dst.writeByte(34);
                    messageReuseBuffer.length = 0;
                    google.protobuf.SourceContext.serializeBytes(localSourceContext, messageReuseBuffer);
                    Serialize.writeVarint32(dst, messageReuseBuffer.length);
                    dst.writeBytes(messageReuseBuffer);
                }
                if (localSyntax)
                {
                    dst.writeByte(40);
                    Serialize.writeInt32(dst, localSyntax);
                }

                if (src.unknownFields)
                    dst.writeBytes(src.unknownFields);
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
