/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    /**
     * Whether a field is optional, required, or repeated.
     */
    public final class FieldCardinality
    {
        /**
         * For fields with unknown cardinality.
         */
        public static const CARDINALITY_UNKNOWN:uint = 0;

        /**
         * For optional fields.
         */
        public static const CARDINALITY_OPTIONAL:uint = 1;

        /**
         * For required fields. Proto2 syntax only.
         */
        public static const CARDINALITY_REQUIRED:uint = 2;

        /**
         * For repeated fields.
         */
        public static const CARDINALITY_REPEATED:uint = 3;
    }
}
