/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * A single field of a message type.
     */
    public final class Field
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Field";

        /**
         * The field type.
         */
        public var kind:int = 0;

        /**
         * The field cardinality.
         */
        public var cardinality:int = 0;

        /**
         * The field number.
         */
        public var number:int = 0;

        /**
         * The field name.
         */
        public var name:String = "";

        /**
         * The field type URL, without the scheme, for message or enumeration
         * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
         */
        public var typeUrl:String = "";

        /**
         * The index of the field type in `Type.oneofs`, for message or enumeration
         * types. The first type has index 1; zero means the type is not in the list.
         */
        public var oneofIndex:int = 0;

        /**
         * Whether to use alternative packed wire representation.
         */
        public var packed:Boolean = false;

        /**
         * The protocol buffer options.
         */
        public var options:Vector.<Option> = new Vector.<Option>();

        /**
         * The field JSON name.
         */
        public var jsonName:String = "";

        /**
         * The string value of the default value of this field. Proto2 syntax only.
         */
        public var defaultValue:String = "";

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Field):void
        {
            msg.kind = 0;
            msg.cardinality = 0;
            msg.number = 0;
            msg.name = "";
            msg.typeUrl = "";
            msg.oneofIndex = 0;
            msg.packed = false;
            msg.options.length = 0;
            msg.jsonName = "";
            msg.defaultValue = "";
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:Field):Field
        {
            if (!src)
                return null;

            const dst:Field = new Field();
            dst.kind = src.kind;
            dst.cardinality = src.cardinality;
            dst.number = src.number;
            dst.name = src.name;
            dst.typeUrl = src.typeUrl;
            dst.oneofIndex = src.oneofIndex;
            dst.packed = src.packed;
            const cloneSource7:Vector.<Option> = src.options;
            const cloneTarget7:Vector.<Option> = dst.options;
            cloneTarget7.length = cloneSource7.length;
            for (var cloneIndex7:uint = 0; cloneIndex7 < cloneSource7.length; cloneIndex7++)
                cloneTarget7[cloneIndex7] = Option.clone(cloneSource7[cloneIndex7]);
            dst.jsonName = src.jsonName;
            dst.defaultValue = src.defaultValue;

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Field = null, limit:uint = 0, reset:Boolean = true):Field
        {
            if (!dst)
                dst = new Field();
            else if (reset)
                Field.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 8:
                    {
                        dst.kind = Deserialize.readInt32(src);
                        break;
                    }
                    case 16:
                    {
                        dst.cardinality = Deserialize.readInt32(src);
                        break;
                    }
                    case 24:
                    {
                        dst.number = Deserialize.readInt32(src);
                        break;
                    }
                    case 34:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 50:
                    {
                        dst.typeUrl = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 56:
                    {
                        dst.oneofIndex = Deserialize.readInt32(src);
                        break;
                    }
                    case 64:
                    {
                        dst.packed = Deserialize.readBool(src);
                        break;
                    }
                    case 74:
                    {
                        const msgOptions:Option = new Option();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Option.deserializeBytes(src, msgOptions, src.position + messageLength);
                        dst.options.push(msgOptions);
                        break;
                    }
                    case 82:
                    {
                        dst.jsonName = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 90:
                    {
                        dst.defaultValue = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Field, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localKind:int = src.kind;
            const localCardinality:int = src.cardinality;
            const localNumber:int = src.number;
            const localName:String = src.name;
            const localTypeUrl:String = src.typeUrl;
            const localOneofIndex:int = src.oneofIndex;
            const localPacked:Boolean = src.packed;
            const localOptions:Vector.<Option> = src.options;
            const localJsonName:String = src.jsonName;
            const localDefaultValue:String = src.defaultValue;

            try
            {
                if (localKind)
                {
                    dst.writeByte(8);
                    Serialize.writeInt32(dst, localKind);
                }
                if (localCardinality)
                {
                    dst.writeByte(16);
                    Serialize.writeInt32(dst, localCardinality);
                }
                if (localNumber)
                {
                    dst.writeByte(24);
                    Serialize.writeInt32(dst, localNumber);
                }
                if (localName)
                {
                    dst.writeByte(34);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if (localTypeUrl)
                {
                    dst.writeByte(50);
                    Serialize.writeString(dst, localTypeUrl, reuseBuffer);
                }
                if (localOneofIndex)
                {
                    dst.writeByte(56);
                    Serialize.writeInt32(dst, localOneofIndex);
                }
                if (localPacked)
                {
                    dst.writeByte(64);
                    dst.writeByte(localPacked ? 1 : 0);
                }
                if ((vecLength = localOptions.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(74);
                        messageReuseBuffer.length = 0;
                        Option.serializeBytes(localOptions[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if (localJsonName)
                {
                    dst.writeByte(82);
                    Serialize.writeString(dst, localJsonName, reuseBuffer);
                }
                if (localDefaultValue)
                {
                    dst.writeByte(90);
                    Serialize.writeString(dst, localDefaultValue, reuseBuffer);
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
