/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    /**
     * Basic field types.
     */
    public final class FieldKind
    {
        /**
         * Field type unknown.
         */
        public static const TYPE_UNKNOWN:uint = 0;

        /**
         * Field type double.
         */
        public static const TYPE_DOUBLE:uint = 1;

        /**
         * Field type float.
         */
        public static const TYPE_FLOAT:uint = 2;

        /**
         * Field type int64.
         */
        public static const TYPE_INT64:uint = 3;

        /**
         * Field type uint64.
         */
        public static const TYPE_UINT64:uint = 4;

        /**
         * Field type int32.
         */
        public static const TYPE_INT32:uint = 5;

        /**
         * Field type fixed64.
         */
        public static const TYPE_FIXED64:uint = 6;

        /**
         * Field type fixed32.
         */
        public static const TYPE_FIXED32:uint = 7;

        /**
         * Field type bool.
         */
        public static const TYPE_BOOL:uint = 8;

        /**
         * Field type string.
         */
        public static const TYPE_STRING:uint = 9;

        /**
         * Field type group. Proto2 syntax only, and deprecated.
         */
        public static const TYPE_GROUP:uint = 10;

        /**
         * Field type message.
         */
        public static const TYPE_MESSAGE:uint = 11;

        /**
         * Field type bytes.
         */
        public static const TYPE_BYTES:uint = 12;

        /**
         * Field type uint32.
         */
        public static const TYPE_UINT32:uint = 13;

        /**
         * Field type enum.
         */
        public static const TYPE_ENUM:uint = 14;

        /**
         * Field type sfixed32.
         */
        public static const TYPE_SFIXED32:uint = 15;

        /**
         * Field type sfixed64.
         */
        public static const TYPE_SFIXED64:uint = 16;

        /**
         * Field type sint32.
         */
        public static const TYPE_SINT32:uint = 17;

        /**
         * Field type sint64.
         */
        public static const TYPE_SINT64:uint = 18;
    }
}
