/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/wrappers.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.types.Int64;
    import as3pb.wkt.AnyRegistry;

    /**
     * Wrapper message for `int64`.
     *
     * The JSON representation for `Int64Value` is JSON string.
     */
    public final class Int64Value
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Int64Value";

        /**
         * The int64 value.
         */
        public var value:Int64 = new Int64();

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Int64Value):void
        {
            msg.value.low = 0;
            msg.value.high = 0;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Int64Value = null, limit:uint = 0, reset:Boolean = true):Int64Value
        {
            if (!dst)
                dst = new Int64Value();
            else if (reset)
                Int64Value.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 8:
                    {
                        Deserialize.readVarint64s(src, dst.value);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Int64Value, dst:ByteArray):void
        {
            if (!src)
                return;

            const localValue:Int64 = src.value;

            if (localValue.low || localValue.high)
            {
                dst.writeByte(8);
                Serialize.writeVarint64s(dst, localValue.low, localValue.high);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
