/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/struct.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * `ListValue` is a wrapper around a repeated field of values.
     *
     * The JSON representation for `ListValue` is JSON array.
     */
    public final class ListValue
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.ListValue";

        /**
         * Repeated field of dynamically typed values.
         */
        public var values:Vector.<Value> = new Vector.<Value>();

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:ListValue):void
        {
            msg.values.length = 0;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:ListValue):ListValue
        {
            if (!src)
                return null;

            const dst:ListValue = new ListValue();
            const cloneSource0:Vector.<Value> = src.values;
            const cloneTarget0:Vector.<Value> = dst.values;
            cloneTarget0.length = cloneSource0.length;
            for (var cloneIndex0:uint = 0; cloneIndex0 < cloneSource0.length; cloneIndex0++)
                cloneTarget0[cloneIndex0] = Value.clone(cloneSource0[cloneIndex0]);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:ListValue = null, limit:uint = 0, reset:Boolean = true):ListValue
        {
            if (!dst)
                dst = new ListValue();
            else if (reset)
                ListValue.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        const msgValues:Value = new Value();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Value.deserializeBytes(src, msgValues, src.position + messageLength);
                        dst.values.push(msgValues);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:ListValue, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localValues:Vector.<Value> = src.values;

            try
            {
                if ((vecLength = localValues.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(10);
                        messageReuseBuffer.length = 0;
                        Value.serializeBytes(localValues[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
