/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/api.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Method represents a method of an API interface.
     */
    public final class Method
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Method";

        /**
         * The simple name of this method.
         */
        public var name:String = "";

        /**
         * A URL of the input message type.
         */
        public var requestTypeUrl:String = "";

        /**
         * If true, the request is streamed.
         */
        public var requestStreaming:Boolean = false;

        /**
         * The URL of the output message type.
         */
        public var responseTypeUrl:String = "";

        /**
         * If true, the response is streamed.
         */
        public var responseStreaming:Boolean = false;

        /**
         * Any metadata attached to the method.
         */
        public var options:Vector.<google.protobuf.Option> = new Vector.<google.protobuf.Option>();

        /**
         * The source syntax of this method.
         */
        public var syntax:int = 0;

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.Method):void
        {
            msg.name = "";
            msg.requestTypeUrl = "";
            msg.requestStreaming = false;
            msg.responseTypeUrl = "";
            msg.responseStreaming = false;
            msg.options.length = 0;
            msg.syntax = 0;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.Method):google.protobuf.Method
        {
            if (!src)
                return null;

            const dst:google.protobuf.Method = new google.protobuf.Method();
            dst.name = src.name;
            dst.requestTypeUrl = src.requestTypeUrl;
            dst.requestStreaming = src.requestStreaming;
            dst.responseTypeUrl = src.responseTypeUrl;
            dst.responseStreaming = src.responseStreaming;
            const cloneSource5:Vector.<google.protobuf.Option> = src.options;
            const cloneTarget5:Vector.<google.protobuf.Option> = dst.options;
            cloneTarget5.length = cloneSource5.length;
            for (var cloneIndex5:uint = 0; cloneIndex5 < cloneSource5.length; cloneIndex5++)
                cloneTarget5[cloneIndex5] = google.protobuf.Option.clone(cloneSource5[cloneIndex5]);
            dst.syntax = src.syntax;
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.Method = null, limit:uint = 0, reset:Boolean = true):google.protobuf.Method
        {
            if (!dst)
                dst = new google.protobuf.Method();
            else if (reset)
                google.protobuf.Method.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        dst.requestTypeUrl = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 24:
                    {
                        dst.requestStreaming = Deserialize.readBool(src);
                        break;
                    }
                    case 34:
                    {
                        dst.responseTypeUrl = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 40:
                    {
                        dst.responseStreaming = Deserialize.readBool(src);
                        break;
                    }
                    case 50:
                    {
                        const msgOptions:google.protobuf.Option = new google.protobuf.Option();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            google.protobuf.Option.deserializeBytes(src, msgOptions, src.position + messageLength);
                        dst.options.push(msgOptions);
                        break;
                    }
                    case 56:
                    {
                        dst.syntax = Deserialize.readInt32(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();
                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.Method, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localRequestTypeUrl:String = src.requestTypeUrl;
            const localRequestStreaming:Boolean = src.requestStreaming;
            const localResponseTypeUrl:String = src.responseTypeUrl;
            const localResponseStreaming:Boolean = src.responseStreaming;
            const localOptions:Vector.<google.protobuf.Option> = src.options;
            const localSyntax:int = src.syntax;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if (localRequestTypeUrl)
                {
                    dst.writeByte(18);
                    Serialize.writeString(dst, localRequestTypeUrl, reuseBuffer);
                }
                if (localRequestStreaming)
                {
                    dst.writeByte(24);
                    dst.writeByte(localRequestStreaming ? 1 : 0);
                }
                if (localResponseTypeUrl)
                {
                    dst.writeByte(34);
                    Serialize.writeString(dst, localResponseTypeUrl, reuseBuffer);
                }
                if (localResponseStreaming)
                {
                    dst.writeByte(40);
                    dst.writeByte(localResponseStreaming ? 1 : 0);
                }
                if ((vecLength = localOptions.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(50);
                        messageReuseBuffer.length = 0;
                        google.protobuf.Option.serializeBytes(localOptions[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if (localSyntax)
                {
                    dst.writeByte(56);
                    Serialize.writeInt32(dst, localSyntax);
                }

                if (src.unknownFields)
                    dst.writeBytes(src.unknownFields);
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
