/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/api.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Declares an API Interface to be included in this interface. The including
     * interface must redeclare all the methods from the included interface, but
     * documentation and options are inherited as follows:
     *
     * - If after comment and whitespace stripping, the documentation
     *   string of the redeclared method is empty, it will be inherited
     *   from the original method.
     *
     * - Each annotation belonging to the service config (http,
     *   visibility) which is not set in the redeclared method will be
     *   inherited.
     *
     * - If an http annotation is inherited, the path pattern will be
     *   modified as follows. Any version prefix will be replaced by the
     *   version of the including interface plus the [root][] path if
     *   specified.
     *
     * Example of a simple mixin:
     *
     *     package google.acl.v1;
     *     service AccessControl {
     *       // Get the underlying ACL object.
     *       rpc GetAcl(GetAclRequest) returns (Acl) {
     *         option (google.api.http).get = "/v1/{resource=**}:getAcl";
     *       }
     *     }
     *
     *     package google.storage.v2;
     *     service Storage {
     *       rpc GetAcl(GetAclRequest) returns (Acl);
     *
     *       // Get a data record.
     *       rpc GetData(GetDataRequest) returns (Data) {
     *         option (google.api.http).get = "/v2/{resource=**}";
     *       }
     *     }
     *
     * Example of a mixin configuration:
     *
     *     apis:
     *     - name: google.storage.v2.Storage
     *       mixins:
     *       - name: google.acl.v1.AccessControl
     *
     * The mixin construct implies that all methods in `AccessControl` are
     * also declared with same name and request/response types in
     * `Storage`. A documentation generator or annotation processor will
     * see the effective `Storage.GetAcl` method after inheriting
     * documentation and annotations as follows:
     *
     *     service Storage {
     *       // Get the underlying ACL object.
     *       rpc GetAcl(GetAclRequest) returns (Acl) {
     *         option (google.api.http).get = "/v2/{resource=**}:getAcl";
     *       }
     *       ...
     *     }
     *
     * Note how the version in the path pattern changed from `v1` to `v2`.
     *
     * If the `root` field in the mixin is specified, it should be a
     * relative path under which inherited HTTP paths are placed. Example:
     *
     *     apis:
     *     - name: google.storage.v2.Storage
     *       mixins:
     *       - name: google.acl.v1.AccessControl
     *         root: acls
     *
     * This implies the following inherited HTTP annotation:
     *
     *     service Storage {
     *       // Get the underlying ACL object.
     *       rpc GetAcl(GetAclRequest) returns (Acl) {
     *         option (google.api.http).get = "/v2/acls/{resource=**}:getAcl";
     *       }
     *       ...
     *     }
     */
    public final class Mixin
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Mixin";

        /**
         * The fully qualified name of the interface which is included.
         */
        public var name:String = "";

        /**
         * If non-empty specifies a path under which inherited HTTP paths
         * are rooted.
         */
        public var root:String = "";

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Mixin):void
        {
            msg.name = "";
            msg.root = "";
            if (msg.unknownFields != null)
                msg.unknownFields.length = 0;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:Mixin):Mixin
        {
            if (!src)
                return null;

            const dst:Mixin = new Mixin();
            dst.name = src.name;
            dst.root = src.root;

            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Mixin = null, limit:uint = 0, reset:Boolean = true):Mixin
        {
            if (!dst)
                dst = new Mixin();
            else if (reset)
                Mixin.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        dst.root = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();
                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Mixin, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;

            const localName:String = src.name;
            const localRoot:String = src.root;

            if (localName)
            {
                dst.writeByte(10);
                Serialize.writeString(dst, localName, reuseBuffer);
            }
            if (localRoot)
            {
                dst.writeByte(18);
                Serialize.writeString(dst, localRoot, reuseBuffer);
            }

            if (src.unknownFields != null && src.unknownFields.length !== 0)
                dst.writeBytes(src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
