/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/struct.proto
 */
package google.protobuf
{
    /**
     * `NullValue` is a singleton enumeration to represent the null value for the
     * `Value` type union.
     *
     *  The JSON representation for `NullValue` is JSON `null`.
     */
    public final class NullValue
    {
        /**
         * Null value.
         */
        public static const NULL_VALUE:uint = 0;
    }
}
