/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import google.protobuf.Any;
    import as3pb.types.AnyRegistry;

    /**
     * A protocol buffer option, which can be attached to a message, field,
     * enumeration, etc.
     */
    public final class Option
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Option";

        /**
         * The option's name. For protobuf built-in options (options defined in
         * descriptor.proto), this is the short name. For example, `"map_entry"`.
         * For custom options, it should be the fully-qualified name. For example,
         * `"google.api.http"`.
         */
        public var name:String = "";

        /**
         * The option's value packed in an Any message. If the value is a primitive,
         * the corresponding wrapper type defined in google/protobuf/wrappers.proto
         * should be used. If the value is an enum, it should be stored as an int32
         * value using the google.protobuf.Int32Value type.
         */
        public var value:Any = null;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Option):void
        {
            msg.name = "";
            msg.value = null;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Option = null, limit:uint = 0, reset:Boolean = true):Option
        {
            if (!dst)
                dst = new Option();
            else if (reset)
                Option.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        messageLength = Deserialize.readVarint32(src);
                        dst.value = Any.deserializeBytes(src, dst.value, src.position + messageLength, false);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Option, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localValue:Any = src.value;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if (localValue)
                {
                    dst.writeByte(18);
                    messageReuseBuffer.length = 0;
                    Any.serializeBytes(localValue, messageReuseBuffer);
                    Serialize.writeVarint32(dst, messageReuseBuffer.length);
                    dst.writeBytes(messageReuseBuffer);
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
