/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Pack;
    import as3pb.proto.PackContext;
    import as3pb.proto.Unpack;
    import as3pb.proto.UnpackContext;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * A protocol buffer option, which can be attached to a message, field,
     * enumeration, etc.
     */
    public final class Option
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Option";

        /**
         * The option's name. For protobuf built-in options (options defined in
         * descriptor.proto), this is the short name. For example, `"map_entry"`.
         * For custom options, it should be the fully-qualified name. For example,
         * `"google.api.http"`.
         */
        public var name:String = "";

        /**
         * The option's value packed in an Any message. If the value is a primitive,
         * the corresponding wrapper type defined in google/protobuf/wrappers.proto
         * should be used. If the value is an enum, it should be stored as an int32
         * value using the google.protobuf.Int32Value type.
         */
        public var value:google.protobuf.Any = null;

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.Option):void
        {
            msg.name = "";
            msg.value = null;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.Option):google.protobuf.Option
        {
            if (!src)
                return null;

            const dst:google.protobuf.Option = new google.protobuf.Option();
            dst.name = src.name;
            dst.value = google.protobuf.Any.clone(src.value);
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Reusable destination message, or null to allocate.
         * @param length Number of bytes to decode from the current position; zero means an empty message.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.Option, length:uint, reset:Boolean = true):google.protobuf.Option
        {
            if (!dst)
                dst = new google.protobuf.Option();
            else if (reset)
                google.protobuf.Option.reset(dst);

            if (!length)
                return dst;
            else if (length > src.bytesAvailable)
                throw new Error("Invalid protobuf message length");

            const end:uint = src.position + length;

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        dst.value = google.protobuf.Any.deserializeBytes(src, dst.value, Deserialize.readVarint32(src), false);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();

                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.Option, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localValue:google.protobuf.Any = src.value;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if (localValue)
                {
                    dst.writeByte(18);
                    messageReuseBuffer.length = 0;
                    google.protobuf.Any.serializeBytes(localValue, messageReuseBuffer);
                    Serialize.writeVarint32(dst, messageReuseBuffer.length);
                    dst.writeBytes(messageReuseBuffer);
                }

                if (src.unknownFields)
                    dst.writeBytes(src.unknownFields);
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The active UnpackContext; bind with Unpack.begin first.
         * @param dst Reusable destination message, or null to allocate.
         * @param length Number of bytes to decode from the current position; zero means an empty message.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeMemory(src:UnpackContext, dst:google.protobuf.Option, length:uint, reset:Boolean = true):google.protobuf.Option
        {
            if (!dst)
                dst = new google.protobuf.Option();
            else if (reset)
                google.protobuf.Option.reset(dst);

            if (!length)
                return dst;
            else if (src.position > src.limit || length > src.limit - src.position)
                throw new Error("Invalid protobuf message length");

            const end:uint = src.position + length;
            const previousLimit:uint = src.limit;
            src.limit = end;
            try
            {

                while (src.position < end)
                {
                    const tag:uint = Unpack.readTag(src);
                    switch (tag)
                    {
                        case 10:
                        {
                            dst.name = Unpack.readString(src);
                            break;
                        }
                        case 18:
                        {
                            dst.value = google.protobuf.Any.deserializeMemory(src, dst.value, Unpack.readVarint32(src), false);
                            break;
                        }
                        default:
                        {
                            if ((tag >>> 3) == 0)
                                throw new Error("Invalid protobuf field number");

                            if (dst.unknownFields == null)
                                dst.unknownFields = Buffers.newByteArray();

                            Unpack.captureUnknownField(src, tag, dst.unknownFields);
                            break;
                        }
                    }
                }

                if (src.position > end)
                    throw new Error("Truncated protobuf message");

            }
            finally
            {
                src.limit = previousLimit;
            }
            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The active PackContext; bind with Pack.begin first.
         */
        public static function serializeMemory(src:google.protobuf.Option, dst:PackContext):void
        {
            if (!src)
                return;

            var messageStart:uint;

            const localName:String = src.name;
            const localValue:google.protobuf.Any = src.value;

            if (localName)
            {
                Pack.writeByte(dst, 10);
                Pack.writeString(dst, localName);
            }
            if (localValue)
            {
                Pack.writeByte(dst, 18);
                messageStart = Pack.startMessage(dst);
                google.protobuf.Any.serializeMemory(localValue, dst);
                Pack.endMessage(dst, messageStart);
            }

            if (src.unknownFields)
                Pack.writeRawBytes(dst, src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
