/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/source_context.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import flash.errors.EOFError;
    import as3pb.proto.Unpack;
    import as3pb.proto.UnpackContext;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * `SourceContext` represents information about the source of a
     * protobuf element, like the file in which it is defined.
     */
    public final class SourceContext
    {
        private static const UNPACK:UnpackContext = new UnpackContext();
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.SourceContext";

        /**
         * The path-qualified name of the .proto file that contained the associated
         * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
         */
        public var fileName:String = "";

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.SourceContext):void
        {
            msg.fileName = "";
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.SourceContext):google.protobuf.SourceContext
        {
            if (!src)
                return null;

            const dst:google.protobuf.SourceContext = new google.protobuf.SourceContext();
            dst.fileName = src.fileName;
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.SourceContext = null, limit:uint = 0, reset:Boolean = true):google.protobuf.SourceContext
        {
            const context:UnpackContext = UNPACK;
            Unpack.begin(context, src, limit);
            try
            {
                dst = deserializeMemory(context, dst, context.limit, reset);
            }
            finally
            {
                Unpack.end(context);
            }
            return dst;
        }

        /** Decode within an active memory binding; nested messages share the context. */
        public static function deserializeMemory(src:UnpackContext, dst:google.protobuf.SourceContext = null, limit:uint = 0, reset:Boolean = true):google.protobuf.SourceContext
        {
            if (!dst)
                dst = new google.protobuf.SourceContext();
            else if (reset)
                google.protobuf.SourceContext.reset(dst);

            const end:uint = limit
                ? limit
                : src.limit;

            if (end < src.position || end > src.limit)
                throw new Error("Invalid protobuf message limit");

            const previousLimit:uint = src.limit;
            src.limit = end;
            try
            {
                while (src.position < end)
                {
                    const tag:uint = Unpack.readTag(src);
                    switch (tag)
                    {
                        case 10:
                        {
                            dst.fileName = Unpack.readString(src);
                            break;
                        }
                        default:
                        {
                            if ((tag >>> 3) == 0)
                                throw new Error("Invalid protobuf field number");

                            if (dst.unknownFields == null)
                                dst.unknownFields = Buffers.newByteArray();

                            Unpack.captureUnknownField(src, tag, dst.unknownFields);
                            break;
                        }
                    }
                }

                if (src.position > end)
                    throw new Error("Truncated protobuf message");

            }
            finally
            {
                src.limit = previousLimit;
            }
            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.SourceContext, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;

            const localFileName:String = src.fileName;

            if (localFileName)
            {
                dst.writeByte(10);
                Serialize.writeString(dst, localFileName, reuseBuffer);
            }

            if (src.unknownFields)
                dst.writeBytes(src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
