/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/source_context.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * `SourceContext` represents information about the source of a
     * protobuf element, like the file in which it is defined.
     */
    public final class SourceContext
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.SourceContext";

        /**
         * The path-qualified name of the .proto file that contained the associated
         * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
         */
        public var fileName:String = "";

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:SourceContext):void
        {
            msg.fileName = "";
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:SourceContext):SourceContext
        {
            if (!src)
                return null;

            const dst:SourceContext = new SourceContext();
            dst.fileName = src.fileName;

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:SourceContext = null, limit:uint = 0, reset:Boolean = true):SourceContext
        {
            if (!dst)
                dst = new SourceContext();
            else if (reset)
                SourceContext.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.fileName = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:SourceContext, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;

            const localFileName:String = src.fileName;

            if (localFileName)
            {
                dst.writeByte(10);
                Serialize.writeString(dst, localFileName, reuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
