/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/wrappers.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * Wrapper message for `string`.
     *
     * The JSON representation for `StringValue` is JSON string.
     */
    public final class StringValue
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.StringValue";

        /**
         * The string value.
         */
        public var value:String = "";

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.StringValue):void
        {
            msg.value = "";
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.StringValue):google.protobuf.StringValue
        {
            if (!src)
                return null;

            const dst:google.protobuf.StringValue = new google.protobuf.StringValue();
            dst.value = src.value;
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.StringValue = null, limit:uint = 0, reset:Boolean = true):google.protobuf.StringValue
        {
            if (!dst)
                dst = new google.protobuf.StringValue();
            else if (reset)
                google.protobuf.StringValue.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.value = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();

                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.StringValue, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;

            const localValue:String = src.value;

            if (localValue)
            {
                dst.writeByte(10);
                Serialize.writeString(dst, localValue, reuseBuffer);
            }

            if (src.unknownFields)
                dst.writeBytes(src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
