/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/struct.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    public final class StructFieldsEntry
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Struct.FieldsEntry";

        public var key:String = "";
        public var value:google.protobuf.Value = null;

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.StructFieldsEntry):void
        {
            msg.key = "";
            msg.value = null;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.StructFieldsEntry):google.protobuf.StructFieldsEntry
        {
            if (!src)
                return null;

            const dst:google.protobuf.StructFieldsEntry = new google.protobuf.StructFieldsEntry();
            dst.key = src.key;
            dst.value = google.protobuf.Value.clone(src.value);
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.StructFieldsEntry = null, limit:uint = 0, reset:Boolean = true):google.protobuf.StructFieldsEntry
        {
            if (!dst)
                dst = new google.protobuf.StructFieldsEntry();
            else if (reset)
                google.protobuf.StructFieldsEntry.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.key = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        messageLength = Deserialize.readVarint32(src);
                        dst.value = google.protobuf.Value.deserializeBytes(src, dst.value, src.position + messageLength, false);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();

                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.StructFieldsEntry, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localKey:String = src.key;
            const localValue:google.protobuf.Value = src.value;

            try
            {
                if (localKey)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localKey, reuseBuffer);
                }
                if (localValue)
                {
                    dst.writeByte(18);
                    messageReuseBuffer.length = 0;
                    google.protobuf.Value.serializeBytes(localValue, messageReuseBuffer);
                    Serialize.writeVarint32(dst, messageReuseBuffer.length);
                    dst.writeBytes(messageReuseBuffer);
                }

                if (src.unknownFields)
                    dst.writeBytes(src.unknownFields);
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
