/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/struct.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.wkt.AnyRegistry;

    /**
     * `Struct` represents a structured data value, consisting of fields
     * which map to dynamically typed values. In some languages, `Struct`
     * might be supported by a native representation. For example, in
     * scripting languages like JS a struct is represented as an
     * object. The details of that representation are described together
     * with the proto support for the language.
     *
     * The JSON representation for `Struct` is JSON object.
     */
    public final class Struct
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Struct";

        /**
         * Unordered map of dynamically typed values.
         */
        public var fields:Vector.<google.protobuf.StructFieldsEntry> = new Vector.<google.protobuf.StructFieldsEntry>();

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.Struct):void
        {
            msg.fields.length = 0;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.Struct):google.protobuf.Struct
        {
            if (!src)
                return null;

            const dst:google.protobuf.Struct = new google.protobuf.Struct();
            const cloneSource0:Vector.<google.protobuf.StructFieldsEntry> = src.fields;
            const cloneTarget0:Vector.<google.protobuf.StructFieldsEntry> = dst.fields;
            cloneTarget0.length = cloneSource0.length;
            for (var cloneIndex0:uint = 0; cloneIndex0 < cloneSource0.length; cloneIndex0++)
                cloneTarget0[cloneIndex0] = google.protobuf.StructFieldsEntry.clone(cloneSource0[cloneIndex0]);
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.Struct = null, limit:uint = 0, reset:Boolean = true):google.protobuf.Struct
        {
            if (!dst)
                dst = new google.protobuf.Struct();
            else if (reset)
                google.protobuf.Struct.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 10:
                    {
                        const msgFields:google.protobuf.StructFieldsEntry = new google.protobuf.StructFieldsEntry();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            google.protobuf.StructFieldsEntry.deserializeBytes(src, msgFields, src.position + messageLength);
                        dst.fields.push(msgFields);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();

                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.Struct, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localFields:Vector.<google.protobuf.StructFieldsEntry> = src.fields;

            try
            {
                if ((vecLength = localFields.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(10);
                        messageReuseBuffer.length = 0;
                        google.protobuf.StructFieldsEntry.serializeBytes(localFields[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }

                if (src.unknownFields)
                    dst.writeBytes(src.unknownFields);
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
