/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/struct.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.types.AnyRegistry;

    /**
     * `Struct` represents a structured data value, consisting of fields
     * which map to dynamically typed values. In some languages, `Struct`
     * might be supported by a native representation. For example, in
     * scripting languages like JS a struct is represented as an
     * object. The details of that representation are described together
     * with the proto support for the language.
     *
     * The JSON representation for `Struct` is JSON object.
     */
    public final class Struct
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Struct";

        /**
         * Unordered map of dynamically typed values.
         */
        public var fields:Vector.<StructFieldsEntry> = new Vector.<StructFieldsEntry>();

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Struct):void
        {
            msg.fields.length = 0;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Struct = null, limit:uint = 0, reset:Boolean = true):Struct
        {
            if (!dst)
                dst = new Struct();
            else if (reset)
                Struct.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 10:
                    {
                        const msgFields:StructFieldsEntry = new StructFieldsEntry();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            StructFieldsEntry.deserializeBytes(src, msgFields, src.position + messageLength);
                        dst.fields.push(msgFields);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Struct, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localFields:Vector.<StructFieldsEntry> = src.fields;

            try
            {
                if ((vecLength = localFields.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(10);
                        messageReuseBuffer.length = 0;
                        StructFieldsEntry.serializeBytes(localFields[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
