/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    /**
     * The syntax in which a protocol buffer element is defined.
     */
    public final class Syntax
    {
        /**
         * Syntax `proto2`.
         */
        public static const SYNTAX_PROTO2:uint = 0;

        /**
         * Syntax `proto3`.
         */
        public static const SYNTAX_PROTO3:uint = 1;
    }
}
