/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/timestamp.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.types.Int64;
    import as3pb.wkt.AnyRegistry;

    /**
     * A Timestamp represents a point in time independent of any time zone or local
     * calendar, encoded as a count of seconds and fractions of seconds at
     * nanosecond resolution. The count is relative to an epoch at UTC midnight on
     * January 1, 1970, in the proleptic Gregorian calendar which extends the
     * Gregorian calendar backwards to year one.
     *
     * All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
     * second table is needed for interpretation, using a [24-hour linear
     * smear](https://developers.google.com/time/smear).
     *
     * The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
     * restricting to that range, we ensure that we can convert to and from [RFC
     * 3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.
     *
     * # Examples
     *
     * Example 1: Compute Timestamp from POSIX `time()`.
     *
     *     Timestamp timestamp;
     *     timestamp.set_seconds(time(NULL));
     *     timestamp.set_nanos(0);
     *
     * Example 2: Compute Timestamp from POSIX `gettimeofday()`.
     *
     *     struct timeval tv;
     *     gettimeofday(&tv, NULL);
     *
     *     Timestamp timestamp;
     *     timestamp.set_seconds(tv.tv_sec);
     *     timestamp.set_nanos(tv.tv_usec * 1000);
     *
     * Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.
     *
     *     FILETIME ft;
     *     GetSystemTimeAsFileTime(&ft);
     *     UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;
     *
     *     // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
     *     // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
     *     Timestamp timestamp;
     *     timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
     *     timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));
     *
     * Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.
     *
     *     long millis = System.currentTimeMillis();
     *
     *     Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
     *         .setNanos((int) ((millis % 1000) * 1000000)).build();
     *
     *
     * Example 5: Compute Timestamp from Java `Instant.now()`.
     *
     *     Instant now = Instant.now();
     *
     *     Timestamp timestamp =
     *         Timestamp.newBuilder().setSeconds(now.getEpochSecond())
     *             .setNanos(now.getNano()).build();
     *
     *
     * Example 6: Compute Timestamp from current time in Python.
     *
     *     timestamp = Timestamp()
     *     timestamp.GetCurrentTime()
     *
     * # JSON Mapping
     *
     * In JSON format, the Timestamp type is encoded as a string in the
     * [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
     * format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
     * where {year} is always expressed using four digits while {month}, {day},
     * {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
     * seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
     * are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
     * is required. A proto3 JSON serializer should always use UTC (as indicated by
     * "Z") when printing the Timestamp type and a proto3 JSON parser should be
     * able to accept both UTC and other timezones (as indicated by an offset).
     *
     * For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
     * 01:30 UTC on January 15, 2017.
     *
     * In JavaScript, one can convert a Date object to this format using the
     * standard
     * [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
     * method. In Python, a standard `datetime.datetime` object can be converted
     * to this format using
     * [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
     * the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
     * the Joda Time's [`ISODateTimeFormat.dateTime()`](
     * http://www.joda.org/joda-time/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime%2D%2D
     * ) to obtain a formatter capable of generating timestamps in this format.
     */
    public final class Timestamp
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Timestamp";

        /**
         * Represents seconds of UTC time since Unix epoch
         * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
         * 9999-12-31T23:59:59Z inclusive.
         */
        public var seconds:Int64 = new Int64();

        /**
         * Non-negative fractions of a second at nanosecond resolution. Negative
         * second values with fractions must still have non-negative nanos values
         * that count forward in time. Must be from 0 to 999,999,999
         * inclusive.
         */
        public var nanos:int = 0;

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.Timestamp):void
        {
            msg.seconds.low = 0;
            msg.seconds.high = 0;
            msg.nanos = 0;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.Timestamp):google.protobuf.Timestamp
        {
            if (!src)
                return null;

            const dst:google.protobuf.Timestamp = new google.protobuf.Timestamp();
            dst.seconds.copyFrom(src.seconds);
            dst.nanos = src.nanos;
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.Timestamp = null, limit:uint = 0, reset:Boolean = true):google.protobuf.Timestamp
        {
            if (!dst)
                dst = new google.protobuf.Timestamp();
            else if (reset)
                google.protobuf.Timestamp.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readTag(src);
                switch (tag)
                {
                    case 8:
                    {
                        Deserialize.readVarint64s(src, dst.seconds);
                        break;
                    }
                    case 16:
                    {
                        dst.nanos = Deserialize.readInt32(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        if (dst.unknownFields == null)
                            dst.unknownFields = Buffers.newByteArray();
                        Deserialize.captureUnknownField(src, tag, dst.unknownFields);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.Timestamp, dst:ByteArray):void
        {
            if (!src)
                return;

            const localSeconds:Int64 = src.seconds;
            const localNanos:int = src.nanos;

            if (localSeconds.low || localSeconds.high)
            {
                dst.writeByte(8);
                Serialize.writeVarint64s(dst, localSeconds.low, localSeconds.high);
            }
            if (localNanos)
            {
                dst.writeByte(16);
                Serialize.writeInt32(dst, localNanos);
            }

            if (src.unknownFields)
                dst.writeBytes(src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
