/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/type.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.types.AnyRegistry;

    /**
     * A protocol buffer message type.
     */
    public final class Type
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Type";

        /**
         * The fully qualified message name.
         */
        public var name:String = "";

        /**
         * The list of fields.
         */
        public var fields:Vector.<Field> = new Vector.<Field>();

        /**
         * The list of types appearing in `oneof` definitions in this type.
         */
        public var oneofs:Vector.<String> = new Vector.<String>();

        /**
         * The protocol buffer options.
         */
        public var options:Vector.<Option> = new Vector.<Option>();

        /**
         * The source context.
         */
        public var sourceContext:SourceContext = null;

        /**
         * The source syntax.
         */
        public var syntax:int = 0;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Type):void
        {
            msg.name = "";
            msg.fields.length = 0;
            msg.oneofs.length = 0;
            msg.options.length = 0;
            msg.sourceContext = null;
            msg.syntax = 0;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Type = null, limit:uint = 0, reset:Boolean = true):Type
        {
            if (!dst)
                dst = new Type();
            else if (reset)
                Type.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 10:
                    {
                        dst.name = src.readUTFBytes(Deserialize.readVarint32(src));
                        break;
                    }
                    case 18:
                    {
                        const msgFields:Field = new Field();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Field.deserializeBytes(src, msgFields, src.position + messageLength);
                        dst.fields.push(msgFields);
                        break;
                    }
                    case 26:
                    {
                        dst.oneofs.push(src.readUTFBytes(Deserialize.readVarint32(src)));
                        break;
                    }
                    case 34:
                    {
                        const msgOptions:Option = new Option();
                        if ((messageLength = Deserialize.readVarint32(src)) !== 0)
                            Option.deserializeBytes(src, msgOptions, src.position + messageLength);
                        dst.options.push(msgOptions);
                        break;
                    }
                    case 42:
                    {
                        messageLength = Deserialize.readVarint32(src);
                        dst.sourceContext = SourceContext.deserializeBytes(src, dst.sourceContext, src.position + messageLength, false);
                        break;
                    }
                    case 48:
                    {
                        dst.syntax = Deserialize.readInt32(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Type, dst:ByteArray):void
        {
            if (!src)
                return;

            var vecIndex:uint = 0;
            var vecLength:uint = 0;
            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localName:String = src.name;
            const localFields:Vector.<Field> = src.fields;
            const localOneofs:Vector.<String> = src.oneofs;
            const localOptions:Vector.<Option> = src.options;
            const localSourceContext:SourceContext = src.sourceContext;
            const localSyntax:int = src.syntax;

            try
            {
                if (localName)
                {
                    dst.writeByte(10);
                    Serialize.writeString(dst, localName, reuseBuffer);
                }
                if ((vecLength = localFields.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(18);
                        messageReuseBuffer.length = 0;
                        Field.serializeBytes(localFields[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if ((vecLength = localOneofs.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(26);
                        Serialize.writeString(dst, localOneofs[vecIndex], reuseBuffer);
                    }
                }
                if ((vecLength = localOptions.length) !== 0)
                {
                    for (vecIndex = 0; vecIndex < vecLength; vecIndex++)
                    {
                        dst.writeByte(34);
                        messageReuseBuffer.length = 0;
                        Option.serializeBytes(localOptions[vecIndex], messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                    }
                }
                if (localSourceContext)
                {
                    dst.writeByte(42);
                    messageReuseBuffer.length = 0;
                    SourceContext.serializeBytes(localSourceContext, messageReuseBuffer);
                    Serialize.writeVarint32(dst, messageReuseBuffer.length);
                    dst.writeBytes(messageReuseBuffer);
                }
                if (localSyntax)
                {
                    dst.writeByte(48);
                    Serialize.writeInt32(dst, localSyntax);
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
