/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/wrappers.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import flash.errors.EOFError;
    import as3pb.proto.Unpack;
    import as3pb.proto.UnpackContext;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.types.UInt64;
    import as3pb.wkt.AnyRegistry;

    /**
     * Wrapper message for `uint64`.
     *
     * The JSON representation for `UInt64Value` is JSON string.
     */
    public final class UInt64Value
    {
        private static const UNPACK:UnpackContext = new UnpackContext();
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.UInt64Value";

        /**
         * The uint64 value.
         */
        public var value:UInt64 = new UInt64();

        /**
         * Raw wire bytes of fields unknown to this schema, preserved from
         * deserialization and re-emitted on serialization. Null when none.
         */
        public var unknownFields:ByteArray;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:google.protobuf.UInt64Value):void
        {
            msg.value.low = 0;
            msg.value.high = 0;
            msg.unknownFields = null;
        }

        /**
         * Creates a deep copy of a message.
         * @param src Message to clone.
         * @return A new deep copy, or null when src is null.
         */
        public static function clone(src:google.protobuf.UInt64Value):google.protobuf.UInt64Value
        {
            if (!src)
                return null;

            const dst:google.protobuf.UInt64Value = new google.protobuf.UInt64Value();
            dst.value.copyFrom(src.value);
            dst.unknownFields = Buffers.cloneByteArray(src.unknownFields);

            return dst;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:google.protobuf.UInt64Value = null, limit:uint = 0, reset:Boolean = true):google.protobuf.UInt64Value
        {
            const context:UnpackContext = UNPACK;
            Unpack.begin(context, src, limit);
            try
            {
                dst = deserializeMemory(context, dst, context.limit, reset);
            }
            finally
            {
                Unpack.end(context);
            }
            return dst;
        }

        /** Decode within an active memory binding; nested messages share the context. */
        public static function deserializeMemory(src:UnpackContext, dst:google.protobuf.UInt64Value = null, limit:uint = 0, reset:Boolean = true):google.protobuf.UInt64Value
        {
            if (!dst)
                dst = new google.protobuf.UInt64Value();
            else if (reset)
                google.protobuf.UInt64Value.reset(dst);

            const end:uint = limit
                ? limit
                : src.limit;

            if (end < src.position || end > src.limit)
                throw new Error("Invalid protobuf message limit");

            const previousLimit:uint = src.limit;
            src.limit = end;
            try
            {
                while (src.position < end)
                {
                    const tag:uint = Unpack.readTag(src);
                    switch (tag)
                    {
                        case 8:
                        {
                            Unpack.readVarint64(src, dst.value);
                            break;
                        }
                        default:
                        {
                            if ((tag >>> 3) == 0)
                                throw new Error("Invalid protobuf field number");

                            if (dst.unknownFields == null)
                                dst.unknownFields = Buffers.newByteArray();

                            Unpack.captureUnknownField(src, tag, dst.unknownFields);
                            break;
                        }
                    }
                }

                if (src.position > end)
                    throw new Error("Truncated protobuf message");

            }
            finally
            {
                src.limit = previousLimit;
            }
            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:google.protobuf.UInt64Value, dst:ByteArray):void
        {
            if (!src)
                return;

            const localValue:UInt64 = src.value;

            if (localValue.low || localValue.high)
            {
                dst.writeByte(8);
                Serialize.writeVarint64(dst, localValue.low, localValue.high);
            }

            if (src.unknownFields)
                dst.writeBytes(src.unknownFields);
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
