/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/wrappers.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.wkt.AnyRegistry;

    /**
     * Wrapper message for `uint32`.
     *
     * The JSON representation for `UInt32Value` is JSON number.
     */
    public final class UInt32Value
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.UInt32Value";

        /**
         * The uint32 value.
         */
        public var value:uint = 0;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:UInt32Value):void
        {
            msg.value = 0;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:UInt32Value = null, limit:uint = 0, reset:Boolean = true):UInt32Value
        {
            if (!dst)
                dst = new UInt32Value();
            else if (reset)
                UInt32Value.reset(dst);

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 8:
                    {
                        dst.value = Deserialize.readVarint32(src);
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:UInt32Value, dst:ByteArray):void
        {
            if (!src)
                return;

            const localValue:uint = src.value;

            if (localValue)
            {
                dst.writeByte(8);
                Serialize.writeVarint32(dst, localValue);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
