/**
 * Code generated by protoc-gen-as3.
 * Source: google/protobuf/struct.proto
 */
package google.protobuf
{
    import flash.utils.ByteArray;
    import as3pb.proto.Deserialize;
    import as3pb.proto.Serialize;
    import as3pb.proto.Buffers;
    import as3pb.types.AnyRegistry;

    /**
     * `Value` represents a dynamically typed value which can be either
     * null, a number, a string, a boolean, a recursive struct value, or a
     * list of values. A producer of value is expected to set one of these
     * variants. Absence of any variant indicates an error.
     *
     * The JSON representation for `Value` is JSON value.
     */
    public final class Value
    {
        public static const TYPE_URL:String = "type.googleapis.com/google.protobuf.Value";

        public static const FIELD_NULL_VALUE:uint = 1;
        public static const FIELD_NUMBER_VALUE:uint = 2;
        public static const FIELD_STRING_VALUE:uint = 3;
        public static const FIELD_BOOL_VALUE:uint = 4;
        public static const FIELD_STRUCT_VALUE:uint = 5;
        public static const FIELD_LIST_VALUE:uint = 6;

        /**
         * Represents a null value.
         */
        public var nullValue:int = 0;

        /**
         * Represents a double value.
         */
        public var numberValue:Number = 0.0;

        /**
         * Represents a string value.
         */
        public var stringValue:String = "";

        /**
         * Represents a boolean value.
         */
        public var boolValue:Boolean = false;

        /**
         * Represents a structured value.
         */
        public var structValue:Struct = null;

        /**
         * Represents a repeated `Value`.
         */
        public var listValue:ListValue = null;

        /**
         * The kind of value.
         * Active case for kind: FIELD_NULL_VALUE, FIELD_NUMBER_VALUE, FIELD_STRING_VALUE, FIELD_BOOL_VALUE, FIELD_STRUCT_VALUE, FIELD_LIST_VALUE.
         */
        public var kindCase:uint;

        /**
         * Resets the message fields to their default values.
         * @param msg The message to reset.
         */
        [Inline]
        public static function reset(msg:Value):void
        {
            msg.nullValue = 0;
            msg.numberValue = 0.0;
            msg.stringValue = "";
            msg.boolValue = false;
            msg.structValue = null;
            msg.listValue = null;
            msg.kindCase = 0;
        }

        /**
         * Deserializes the message from protobuf wire format.
         * @param src The source ByteArray.
         * @param dst Optional reusable destination message.
         * @param limit Optional end position; zero means the remaining bytes.
         * @param reset Whether to reset a reusable destination before decoding.
         */
        public static function deserializeBytes(src:ByteArray, dst:Value = null, limit:uint = 0, reset:Boolean = true):Value
        {
            if (!dst)
                dst = new Value();
            else if (reset)
                Value.reset(dst);

            var messageLength:uint = 0;

            const end:uint = limit
                ? limit
                : src.position + src.bytesAvailable;

            if (end < src.position || end > src.length)
                throw new Error("Invalid protobuf message limit");

            while (src.position < end)
            {
                const tag:uint = Deserialize.readVarint32(src);
                switch (tag)
                {
                    case 8:
                    {
                        dst.nullValue = Deserialize.readInt32(src);
                        dst.kindCase = FIELD_NULL_VALUE;
                        break;
                    }
                    case 17:
                    {
                        dst.numberValue = src.readDouble();
                        dst.kindCase = FIELD_NUMBER_VALUE;
                        break;
                    }
                    case 26:
                    {
                        dst.stringValue = src.readUTFBytes(Deserialize.readVarint32(src));
                        dst.kindCase = FIELD_STRING_VALUE;
                        break;
                    }
                    case 32:
                    {
                        dst.boolValue = Deserialize.readVarint32(src) !== 0;
                        dst.kindCase = FIELD_BOOL_VALUE;
                        break;
                    }
                    case 42:
                    {
                        messageLength = Deserialize.readVarint32(src);
                        dst.structValue = Struct.deserializeBytes(src, dst.structValue, src.position + messageLength, dst.kindCase != FIELD_STRUCT_VALUE);
                        dst.kindCase = FIELD_STRUCT_VALUE;
                        break;
                    }
                    case 50:
                    {
                        messageLength = Deserialize.readVarint32(src);
                        dst.listValue = ListValue.deserializeBytes(src, dst.listValue, src.position + messageLength, dst.kindCase != FIELD_LIST_VALUE);
                        dst.kindCase = FIELD_LIST_VALUE;
                        break;
                    }
                    default:
                    {
                        if ((tag >>> 3) == 0)
                            throw new Error("Invalid protobuf field number");

                        Deserialize.skipField(src, tag & 7);
                        break;
                    }
                }
            }

            if (src.position > end)
                throw new Error("Truncated protobuf message");

            return dst;
        }

        /**
         * Serializes the message to protobuf wire format.
         * @param src The message to serialize; null writes an empty payload.
         * @param dst The destination ByteArray.
         */
        public static function serializeBytes(src:Value, dst:ByteArray):void
        {
            if (!src)
                return;

            const reuseBuffer:ByteArray = Buffers.SHARED_BUFFER;
            const messageReuseBuffer:ByteArray = Buffers.acquireMessageBuffer();

            const localNullValue:int = src.nullValue;
            const localNumberValue:Number = src.numberValue;
            const localStringValue:String = src.stringValue;
            const localBoolValue:Boolean = src.boolValue;
            const localStructValue:Struct = src.structValue;
            const localListValue:ListValue = src.listValue;

            try
            {
                switch (src.kindCase)
                {
                    case FIELD_NULL_VALUE:
                    {
                        dst.writeByte(8);
                        Serialize.writeInt32(dst, localNullValue);
                        break;
                    }
                    case FIELD_NUMBER_VALUE:
                    {
                        dst.writeByte(17);
                        dst.writeDouble(localNumberValue);
                        break;
                    }
                    case FIELD_STRING_VALUE:
                    {
                        dst.writeByte(26);
                        Serialize.writeString(dst, localStringValue, reuseBuffer);
                        break;
                    }
                    case FIELD_BOOL_VALUE:
                    {
                        dst.writeByte(32);
                        dst.writeByte(localBoolValue ? 1 : 0);
                        break;
                    }
                    case FIELD_STRUCT_VALUE:
                    {
                        dst.writeByte(42);
                        messageReuseBuffer.length = 0;
                        Struct.serializeBytes(localStructValue, messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                        break;
                    }
                    case FIELD_LIST_VALUE:
                    {
                        dst.writeByte(50);
                        messageReuseBuffer.length = 0;
                        ListValue.serializeBytes(localListValue, messageReuseBuffer);
                        Serialize.writeVarint32(dst, messageReuseBuffer.length);
                        dst.writeBytes(messageReuseBuffer);
                        break;
                    }
                }
            }
            finally
            {
                Buffers.releaseMessageBuffer(messageReuseBuffer);
            }
        }

        {
            AnyRegistry.register(TYPE_URL, deserializeBytes, serializeBytes);
        }
    }
}
